
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Administradores
 * 
 */
export type Administradores = Prisma.AdministradoresModel
/**
 * Model Compradores
 * 
 */
export type Compradores = Prisma.CompradoresModel
/**
 * Model Libros
 * 
 */
export type Libros = Prisma.LibrosModel
/**
 * Model LibroDigitalAdquirido
 * 
 */
export type LibroDigitalAdquirido = Prisma.LibroDigitalAdquiridoModel
/**
 * Model Proveedores
 * 
 */
export type Proveedores = Prisma.ProveedoresModel
/**
 * Model TiposUsuario
 * 
 */
export type TiposUsuario = Prisma.TiposUsuarioModel
/**
 * Model ListaProveedor
 * 
 */
export type ListaProveedor = Prisma.ListaProveedorModel
/**
 * Model Usuarios
 * 
 */
export type Usuarios = Prisma.UsuariosModel
/**
 * Model OfertaLibro
 * 
 */
export type OfertaLibro = Prisma.OfertaLibroModel
/**
 * Model Carritos
 * 
 */
export type Carritos = Prisma.CarritosModel
/**
 * Model DetallesCarrito
 * 
 */
export type DetallesCarrito = Prisma.DetallesCarritoModel
/**
 * Model Transacciones
 * 
 */
export type Transacciones = Prisma.TransaccionesModel
/**
 * Model DetalleTransaccion
 * 
 */
export type DetalleTransaccion = Prisma.DetalleTransaccionModel
