
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Administradores` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Administradores
 * 
 */
export type AdministradoresModel = runtime.Types.Result.DefaultSelection<Prisma.$AdministradoresPayload>

export type AggregateAdministradores = {
  _count: AdministradoresCountAggregateOutputType | null
  _avg: AdministradoresAvgAggregateOutputType | null
  _sum: AdministradoresSumAggregateOutputType | null
  _min: AdministradoresMinAggregateOutputType | null
  _max: AdministradoresMaxAggregateOutputType | null
}

export type AdministradoresAvgAggregateOutputType = {
  usuario_id: number | null
}

export type AdministradoresSumAggregateOutputType = {
  usuario_id: number | null
}

export type AdministradoresMinAggregateOutputType = {
  usuario_id: number | null
}

export type AdministradoresMaxAggregateOutputType = {
  usuario_id: number | null
}

export type AdministradoresCountAggregateOutputType = {
  usuario_id: number
  _all: number
}


export type AdministradoresAvgAggregateInputType = {
  usuario_id?: true
}

export type AdministradoresSumAggregateInputType = {
  usuario_id?: true
}

export type AdministradoresMinAggregateInputType = {
  usuario_id?: true
}

export type AdministradoresMaxAggregateInputType = {
  usuario_id?: true
}

export type AdministradoresCountAggregateInputType = {
  usuario_id?: true
  _all?: true
}

export type AdministradoresAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Administradores to aggregate.
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Administradores to fetch.
   */
  orderBy?: Prisma.AdministradoresOrderByWithRelationInput | Prisma.AdministradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdministradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Administradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Administradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Administradores
  **/
  _count?: true | AdministradoresCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AdministradoresAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AdministradoresSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdministradoresMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdministradoresMaxAggregateInputType
}

export type GetAdministradoresAggregateType<T extends AdministradoresAggregateArgs> = {
      [P in keyof T & keyof AggregateAdministradores]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdministradores[P]>
    : Prisma.GetScalarType<T[P], AggregateAdministradores[P]>
}




export type AdministradoresGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdministradoresWhereInput
  orderBy?: Prisma.AdministradoresOrderByWithAggregationInput | Prisma.AdministradoresOrderByWithAggregationInput[]
  by: Prisma.AdministradoresScalarFieldEnum[] | Prisma.AdministradoresScalarFieldEnum
  having?: Prisma.AdministradoresScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdministradoresCountAggregateInputType | true
  _avg?: AdministradoresAvgAggregateInputType
  _sum?: AdministradoresSumAggregateInputType
  _min?: AdministradoresMinAggregateInputType
  _max?: AdministradoresMaxAggregateInputType
}

export type AdministradoresGroupByOutputType = {
  usuario_id: number
  _count: AdministradoresCountAggregateOutputType | null
  _avg: AdministradoresAvgAggregateOutputType | null
  _sum: AdministradoresSumAggregateOutputType | null
  _min: AdministradoresMinAggregateOutputType | null
  _max: AdministradoresMaxAggregateOutputType | null
}

export type GetAdministradoresGroupByPayload<T extends AdministradoresGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdministradoresGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdministradoresGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdministradoresGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdministradoresGroupByOutputType[P]>
      }
    >
  >



export type AdministradoresWhereInput = {
  AND?: Prisma.AdministradoresWhereInput | Prisma.AdministradoresWhereInput[]
  OR?: Prisma.AdministradoresWhereInput[]
  NOT?: Prisma.AdministradoresWhereInput | Prisma.AdministradoresWhereInput[]
  usuario_id?: Prisma.IntFilter<"Administradores"> | number
  Usuarios?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
}

export type AdministradoresOrderByWithRelationInput = {
  usuario_id?: Prisma.SortOrder
  Usuarios?: Prisma.UsuariosOrderByWithRelationInput
}

export type AdministradoresWhereUniqueInput = Prisma.AtLeast<{
  usuario_id?: number
  AND?: Prisma.AdministradoresWhereInput | Prisma.AdministradoresWhereInput[]
  OR?: Prisma.AdministradoresWhereInput[]
  NOT?: Prisma.AdministradoresWhereInput | Prisma.AdministradoresWhereInput[]
  Usuarios?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
}, "usuario_id">

export type AdministradoresOrderByWithAggregationInput = {
  usuario_id?: Prisma.SortOrder
  _count?: Prisma.AdministradoresCountOrderByAggregateInput
  _avg?: Prisma.AdministradoresAvgOrderByAggregateInput
  _max?: Prisma.AdministradoresMaxOrderByAggregateInput
  _min?: Prisma.AdministradoresMinOrderByAggregateInput
  _sum?: Prisma.AdministradoresSumOrderByAggregateInput
}

export type AdministradoresScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdministradoresScalarWhereWithAggregatesInput | Prisma.AdministradoresScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdministradoresScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdministradoresScalarWhereWithAggregatesInput | Prisma.AdministradoresScalarWhereWithAggregatesInput[]
  usuario_id?: Prisma.IntWithAggregatesFilter<"Administradores"> | number
}

export type AdministradoresCreateInput = {
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutAdministradoresInput
}

export type AdministradoresUncheckedCreateInput = {
  usuario_id: number
}

export type AdministradoresUpdateInput = {
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutAdministradoresNestedInput
}

export type AdministradoresUncheckedUpdateInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AdministradoresCreateManyInput = {
  usuario_id: number
}

export type AdministradoresUpdateManyMutationInput = {

}

export type AdministradoresUncheckedUpdateManyInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AdministradoresCountOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type AdministradoresAvgOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type AdministradoresMaxOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type AdministradoresMinOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type AdministradoresSumOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type AdministradoresNullableScalarRelationFilter = {
  is?: Prisma.AdministradoresWhereInput | null
  isNot?: Prisma.AdministradoresWhereInput | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AdministradoresCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.AdministradoresCreateWithoutUsuariosInput, Prisma.AdministradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.AdministradoresCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.AdministradoresWhereUniqueInput
}

export type AdministradoresUncheckedCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.AdministradoresCreateWithoutUsuariosInput, Prisma.AdministradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.AdministradoresCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.AdministradoresWhereUniqueInput
}

export type AdministradoresUpdateOneWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.AdministradoresCreateWithoutUsuariosInput, Prisma.AdministradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.AdministradoresCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.AdministradoresUpsertWithoutUsuariosInput
  disconnect?: Prisma.AdministradoresWhereInput | boolean
  delete?: Prisma.AdministradoresWhereInput | boolean
  connect?: Prisma.AdministradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AdministradoresUpdateToOneWithWhereWithoutUsuariosInput, Prisma.AdministradoresUpdateWithoutUsuariosInput>, Prisma.AdministradoresUncheckedUpdateWithoutUsuariosInput>
}

export type AdministradoresUncheckedUpdateOneWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.AdministradoresCreateWithoutUsuariosInput, Prisma.AdministradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.AdministradoresCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.AdministradoresUpsertWithoutUsuariosInput
  disconnect?: Prisma.AdministradoresWhereInput | boolean
  delete?: Prisma.AdministradoresWhereInput | boolean
  connect?: Prisma.AdministradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AdministradoresUpdateToOneWithWhereWithoutUsuariosInput, Prisma.AdministradoresUpdateWithoutUsuariosInput>, Prisma.AdministradoresUncheckedUpdateWithoutUsuariosInput>
}

export type AdministradoresCreateWithoutUsuariosInput = {

}

export type AdministradoresUncheckedCreateWithoutUsuariosInput = {

}

export type AdministradoresCreateOrConnectWithoutUsuariosInput = {
  where: Prisma.AdministradoresWhereUniqueInput
  create: Prisma.XOR<Prisma.AdministradoresCreateWithoutUsuariosInput, Prisma.AdministradoresUncheckedCreateWithoutUsuariosInput>
}

export type AdministradoresUpsertWithoutUsuariosInput = {
  update: Prisma.XOR<Prisma.AdministradoresUpdateWithoutUsuariosInput, Prisma.AdministradoresUncheckedUpdateWithoutUsuariosInput>
  create: Prisma.XOR<Prisma.AdministradoresCreateWithoutUsuariosInput, Prisma.AdministradoresUncheckedCreateWithoutUsuariosInput>
  where?: Prisma.AdministradoresWhereInput
}

export type AdministradoresUpdateToOneWithWhereWithoutUsuariosInput = {
  where?: Prisma.AdministradoresWhereInput
  data: Prisma.XOR<Prisma.AdministradoresUpdateWithoutUsuariosInput, Prisma.AdministradoresUncheckedUpdateWithoutUsuariosInput>
}

export type AdministradoresUpdateWithoutUsuariosInput = {

}

export type AdministradoresUncheckedUpdateWithoutUsuariosInput = {

}



export type AdministradoresSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["administradores"]>

export type AdministradoresSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["administradores"]>

export type AdministradoresSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["administradores"]>

export type AdministradoresSelectScalar = {
  usuario_id?: boolean
}

export type AdministradoresOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"usuario_id", ExtArgs["result"]["administradores"]>
export type AdministradoresInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type AdministradoresIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type AdministradoresIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}

export type $AdministradoresPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Administradores"
  objects: {
    Usuarios: Prisma.$UsuariosPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    usuario_id: number
  }, ExtArgs["result"]["administradores"]>
  composites: {}
}

export type AdministradoresGetPayload<S extends boolean | null | undefined | AdministradoresDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload, S>

export type AdministradoresCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdministradoresFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdministradoresCountAggregateInputType | true
  }

export interface AdministradoresDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Administradores'], meta: { name: 'Administradores' } }
  /**
   * Find zero or one Administradores that matches the filter.
   * @param {AdministradoresFindUniqueArgs} args - Arguments to find a Administradores
   * @example
   * // Get one Administradores
   * const administradores = await prisma.administradores.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdministradoresFindUniqueArgs>(args: Prisma.SelectSubset<T, AdministradoresFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Administradores that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdministradoresFindUniqueOrThrowArgs} args - Arguments to find a Administradores
   * @example
   * // Get one Administradores
   * const administradores = await prisma.administradores.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdministradoresFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdministradoresFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Administradores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresFindFirstArgs} args - Arguments to find a Administradores
   * @example
   * // Get one Administradores
   * const administradores = await prisma.administradores.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdministradoresFindFirstArgs>(args?: Prisma.SelectSubset<T, AdministradoresFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Administradores that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresFindFirstOrThrowArgs} args - Arguments to find a Administradores
   * @example
   * // Get one Administradores
   * const administradores = await prisma.administradores.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdministradoresFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdministradoresFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Administradores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Administradores
   * const administradores = await prisma.administradores.findMany()
   * 
   * // Get first 10 Administradores
   * const administradores = await prisma.administradores.findMany({ take: 10 })
   * 
   * // Only select the `usuario_id`
   * const administradoresWithUsuario_idOnly = await prisma.administradores.findMany({ select: { usuario_id: true } })
   * 
   */
  findMany<T extends AdministradoresFindManyArgs>(args?: Prisma.SelectSubset<T, AdministradoresFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Administradores.
   * @param {AdministradoresCreateArgs} args - Arguments to create a Administradores.
   * @example
   * // Create one Administradores
   * const Administradores = await prisma.administradores.create({
   *   data: {
   *     // ... data to create a Administradores
   *   }
   * })
   * 
   */
  create<T extends AdministradoresCreateArgs>(args: Prisma.SelectSubset<T, AdministradoresCreateArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Administradores.
   * @param {AdministradoresCreateManyArgs} args - Arguments to create many Administradores.
   * @example
   * // Create many Administradores
   * const administradores = await prisma.administradores.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdministradoresCreateManyArgs>(args?: Prisma.SelectSubset<T, AdministradoresCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Administradores and returns the data saved in the database.
   * @param {AdministradoresCreateManyAndReturnArgs} args - Arguments to create many Administradores.
   * @example
   * // Create many Administradores
   * const administradores = await prisma.administradores.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Administradores and only return the `usuario_id`
   * const administradoresWithUsuario_idOnly = await prisma.administradores.createManyAndReturn({
   *   select: { usuario_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AdministradoresCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AdministradoresCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Administradores.
   * @param {AdministradoresDeleteArgs} args - Arguments to delete one Administradores.
   * @example
   * // Delete one Administradores
   * const Administradores = await prisma.administradores.delete({
   *   where: {
   *     // ... filter to delete one Administradores
   *   }
   * })
   * 
   */
  delete<T extends AdministradoresDeleteArgs>(args: Prisma.SelectSubset<T, AdministradoresDeleteArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Administradores.
   * @param {AdministradoresUpdateArgs} args - Arguments to update one Administradores.
   * @example
   * // Update one Administradores
   * const administradores = await prisma.administradores.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdministradoresUpdateArgs>(args: Prisma.SelectSubset<T, AdministradoresUpdateArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Administradores.
   * @param {AdministradoresDeleteManyArgs} args - Arguments to filter Administradores to delete.
   * @example
   * // Delete a few Administradores
   * const { count } = await prisma.administradores.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdministradoresDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdministradoresDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Administradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Administradores
   * const administradores = await prisma.administradores.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdministradoresUpdateManyArgs>(args: Prisma.SelectSubset<T, AdministradoresUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Administradores and returns the data updated in the database.
   * @param {AdministradoresUpdateManyAndReturnArgs} args - Arguments to update many Administradores.
   * @example
   * // Update many Administradores
   * const administradores = await prisma.administradores.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Administradores and only return the `usuario_id`
   * const administradoresWithUsuario_idOnly = await prisma.administradores.updateManyAndReturn({
   *   select: { usuario_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AdministradoresUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AdministradoresUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Administradores.
   * @param {AdministradoresUpsertArgs} args - Arguments to update or create a Administradores.
   * @example
   * // Update or create a Administradores
   * const administradores = await prisma.administradores.upsert({
   *   create: {
   *     // ... data to create a Administradores
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Administradores we want to update
   *   }
   * })
   */
  upsert<T extends AdministradoresUpsertArgs>(args: Prisma.SelectSubset<T, AdministradoresUpsertArgs<ExtArgs>>): Prisma.Prisma__AdministradoresClient<runtime.Types.Result.GetResult<Prisma.$AdministradoresPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Administradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresCountArgs} args - Arguments to filter Administradores to count.
   * @example
   * // Count the number of Administradores
   * const count = await prisma.administradores.count({
   *   where: {
   *     // ... the filter for the Administradores we want to count
   *   }
   * })
  **/
  count<T extends AdministradoresCountArgs>(
    args?: Prisma.Subset<T, AdministradoresCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdministradoresCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Administradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdministradoresAggregateArgs>(args: Prisma.Subset<T, AdministradoresAggregateArgs>): Prisma.PrismaPromise<GetAdministradoresAggregateType<T>>

  /**
   * Group by Administradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdministradoresGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdministradoresGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdministradoresGroupByArgs['orderBy'] }
      : { orderBy?: AdministradoresGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdministradoresGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdministradoresGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Administradores model
 */
readonly fields: AdministradoresFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Administradores.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdministradoresClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Usuarios<T extends Prisma.UsuariosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuariosDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Administradores model
 */
export interface AdministradoresFieldRefs {
  readonly usuario_id: Prisma.FieldRef<"Administradores", 'Int'>
}
    

// Custom InputTypes
/**
 * Administradores findUnique
 */
export type AdministradoresFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * Filter, which Administradores to fetch.
   */
  where: Prisma.AdministradoresWhereUniqueInput
}

/**
 * Administradores findUniqueOrThrow
 */
export type AdministradoresFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * Filter, which Administradores to fetch.
   */
  where: Prisma.AdministradoresWhereUniqueInput
}

/**
 * Administradores findFirst
 */
export type AdministradoresFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * Filter, which Administradores to fetch.
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Administradores to fetch.
   */
  orderBy?: Prisma.AdministradoresOrderByWithRelationInput | Prisma.AdministradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Administradores.
   */
  cursor?: Prisma.AdministradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Administradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Administradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Administradores.
   */
  distinct?: Prisma.AdministradoresScalarFieldEnum | Prisma.AdministradoresScalarFieldEnum[]
}

/**
 * Administradores findFirstOrThrow
 */
export type AdministradoresFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * Filter, which Administradores to fetch.
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Administradores to fetch.
   */
  orderBy?: Prisma.AdministradoresOrderByWithRelationInput | Prisma.AdministradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Administradores.
   */
  cursor?: Prisma.AdministradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Administradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Administradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Administradores.
   */
  distinct?: Prisma.AdministradoresScalarFieldEnum | Prisma.AdministradoresScalarFieldEnum[]
}

/**
 * Administradores findMany
 */
export type AdministradoresFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * Filter, which Administradores to fetch.
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Administradores to fetch.
   */
  orderBy?: Prisma.AdministradoresOrderByWithRelationInput | Prisma.AdministradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Administradores.
   */
  cursor?: Prisma.AdministradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Administradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Administradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Administradores.
   */
  distinct?: Prisma.AdministradoresScalarFieldEnum | Prisma.AdministradoresScalarFieldEnum[]
}

/**
 * Administradores create
 */
export type AdministradoresCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * The data needed to create a Administradores.
   */
  data: Prisma.XOR<Prisma.AdministradoresCreateInput, Prisma.AdministradoresUncheckedCreateInput>
}

/**
 * Administradores createMany
 */
export type AdministradoresCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Administradores.
   */
  data: Prisma.AdministradoresCreateManyInput | Prisma.AdministradoresCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Administradores createManyAndReturn
 */
export type AdministradoresCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * The data used to create many Administradores.
   */
  data: Prisma.AdministradoresCreateManyInput | Prisma.AdministradoresCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Administradores update
 */
export type AdministradoresUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * The data needed to update a Administradores.
   */
  data: Prisma.XOR<Prisma.AdministradoresUpdateInput, Prisma.AdministradoresUncheckedUpdateInput>
  /**
   * Choose, which Administradores to update.
   */
  where: Prisma.AdministradoresWhereUniqueInput
}

/**
 * Administradores updateMany
 */
export type AdministradoresUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Administradores.
   */
  data: Prisma.XOR<Prisma.AdministradoresUpdateManyMutationInput, Prisma.AdministradoresUncheckedUpdateManyInput>
  /**
   * Filter which Administradores to update
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * Limit how many Administradores to update.
   */
  limit?: number
}

/**
 * Administradores updateManyAndReturn
 */
export type AdministradoresUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * The data used to update Administradores.
   */
  data: Prisma.XOR<Prisma.AdministradoresUpdateManyMutationInput, Prisma.AdministradoresUncheckedUpdateManyInput>
  /**
   * Filter which Administradores to update
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * Limit how many Administradores to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Administradores upsert
 */
export type AdministradoresUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * The filter to search for the Administradores to update in case it exists.
   */
  where: Prisma.AdministradoresWhereUniqueInput
  /**
   * In case the Administradores found by the `where` argument doesn't exist, create a new Administradores with this data.
   */
  create: Prisma.XOR<Prisma.AdministradoresCreateInput, Prisma.AdministradoresUncheckedCreateInput>
  /**
   * In case the Administradores was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdministradoresUpdateInput, Prisma.AdministradoresUncheckedUpdateInput>
}

/**
 * Administradores delete
 */
export type AdministradoresDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
  /**
   * Filter which Administradores to delete.
   */
  where: Prisma.AdministradoresWhereUniqueInput
}

/**
 * Administradores deleteMany
 */
export type AdministradoresDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Administradores to delete
   */
  where?: Prisma.AdministradoresWhereInput
  /**
   * Limit how many Administradores to delete.
   */
  limit?: number
}

/**
 * Administradores without action
 */
export type AdministradoresDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Administradores
   */
  select?: Prisma.AdministradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Administradores
   */
  omit?: Prisma.AdministradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdministradoresInclude<ExtArgs> | null
}
