
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Compradores` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Compradores
 * 
 */
export type CompradoresModel = runtime.Types.Result.DefaultSelection<Prisma.$CompradoresPayload>

export type AggregateCompradores = {
  _count: CompradoresCountAggregateOutputType | null
  _avg: CompradoresAvgAggregateOutputType | null
  _sum: CompradoresSumAggregateOutputType | null
  _min: CompradoresMinAggregateOutputType | null
  _max: CompradoresMaxAggregateOutputType | null
}

export type CompradoresAvgAggregateOutputType = {
  usuario_id: number | null
}

export type CompradoresSumAggregateOutputType = {
  usuario_id: number | null
}

export type CompradoresMinAggregateOutputType = {
  usuario_id: number | null
}

export type CompradoresMaxAggregateOutputType = {
  usuario_id: number | null
}

export type CompradoresCountAggregateOutputType = {
  usuario_id: number
  _all: number
}


export type CompradoresAvgAggregateInputType = {
  usuario_id?: true
}

export type CompradoresSumAggregateInputType = {
  usuario_id?: true
}

export type CompradoresMinAggregateInputType = {
  usuario_id?: true
}

export type CompradoresMaxAggregateInputType = {
  usuario_id?: true
}

export type CompradoresCountAggregateInputType = {
  usuario_id?: true
  _all?: true
}

export type CompradoresAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Compradores to aggregate.
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Compradores to fetch.
   */
  orderBy?: Prisma.CompradoresOrderByWithRelationInput | Prisma.CompradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CompradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Compradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Compradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Compradores
  **/
  _count?: true | CompradoresCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CompradoresAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CompradoresSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CompradoresMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CompradoresMaxAggregateInputType
}

export type GetCompradoresAggregateType<T extends CompradoresAggregateArgs> = {
      [P in keyof T & keyof AggregateCompradores]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCompradores[P]>
    : Prisma.GetScalarType<T[P], AggregateCompradores[P]>
}




export type CompradoresGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompradoresWhereInput
  orderBy?: Prisma.CompradoresOrderByWithAggregationInput | Prisma.CompradoresOrderByWithAggregationInput[]
  by: Prisma.CompradoresScalarFieldEnum[] | Prisma.CompradoresScalarFieldEnum
  having?: Prisma.CompradoresScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CompradoresCountAggregateInputType | true
  _avg?: CompradoresAvgAggregateInputType
  _sum?: CompradoresSumAggregateInputType
  _min?: CompradoresMinAggregateInputType
  _max?: CompradoresMaxAggregateInputType
}

export type CompradoresGroupByOutputType = {
  usuario_id: number
  _count: CompradoresCountAggregateOutputType | null
  _avg: CompradoresAvgAggregateOutputType | null
  _sum: CompradoresSumAggregateOutputType | null
  _min: CompradoresMinAggregateOutputType | null
  _max: CompradoresMaxAggregateOutputType | null
}

export type GetCompradoresGroupByPayload<T extends CompradoresGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CompradoresGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CompradoresGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CompradoresGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CompradoresGroupByOutputType[P]>
      }
    >
  >



export type CompradoresWhereInput = {
  AND?: Prisma.CompradoresWhereInput | Prisma.CompradoresWhereInput[]
  OR?: Prisma.CompradoresWhereInput[]
  NOT?: Prisma.CompradoresWhereInput | Prisma.CompradoresWhereInput[]
  usuario_id?: Prisma.IntFilter<"Compradores"> | number
  Carrito?: Prisma.XOR<Prisma.CarritosNullableScalarRelationFilter, Prisma.CarritosWhereInput> | null
  Usuarios?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoListRelationFilter
  transacciones?: Prisma.TransaccionesListRelationFilter
}

export type CompradoresOrderByWithRelationInput = {
  usuario_id?: Prisma.SortOrder
  Carrito?: Prisma.CarritosOrderByWithRelationInput
  Usuarios?: Prisma.UsuariosOrderByWithRelationInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoOrderByRelationAggregateInput
  transacciones?: Prisma.TransaccionesOrderByRelationAggregateInput
}

export type CompradoresWhereUniqueInput = Prisma.AtLeast<{
  usuario_id?: number
  AND?: Prisma.CompradoresWhereInput | Prisma.CompradoresWhereInput[]
  OR?: Prisma.CompradoresWhereInput[]
  NOT?: Prisma.CompradoresWhereInput | Prisma.CompradoresWhereInput[]
  Carrito?: Prisma.XOR<Prisma.CarritosNullableScalarRelationFilter, Prisma.CarritosWhereInput> | null
  Usuarios?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoListRelationFilter
  transacciones?: Prisma.TransaccionesListRelationFilter
}, "usuario_id">

export type CompradoresOrderByWithAggregationInput = {
  usuario_id?: Prisma.SortOrder
  _count?: Prisma.CompradoresCountOrderByAggregateInput
  _avg?: Prisma.CompradoresAvgOrderByAggregateInput
  _max?: Prisma.CompradoresMaxOrderByAggregateInput
  _min?: Prisma.CompradoresMinOrderByAggregateInput
  _sum?: Prisma.CompradoresSumOrderByAggregateInput
}

export type CompradoresScalarWhereWithAggregatesInput = {
  AND?: Prisma.CompradoresScalarWhereWithAggregatesInput | Prisma.CompradoresScalarWhereWithAggregatesInput[]
  OR?: Prisma.CompradoresScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CompradoresScalarWhereWithAggregatesInput | Prisma.CompradoresScalarWhereWithAggregatesInput[]
  usuario_id?: Prisma.IntWithAggregatesFilter<"Compradores"> | number
}

export type CompradoresCreateInput = {
  Carrito?: Prisma.CarritosCreateNestedOneWithoutCompradoresInput
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesCreateNestedManyWithoutCompradorInput
}

export type CompradoresUncheckedCreateInput = {
  usuario_id: number
  Carrito?: Prisma.CarritosUncheckedCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesUncheckedCreateNestedManyWithoutCompradorInput
}

export type CompradoresUpdateInput = {
  Carrito?: Prisma.CarritosUpdateOneWithoutCompradoresNestedInput
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUpdateManyWithoutCompradorNestedInput
}

export type CompradoresUncheckedUpdateInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  Carrito?: Prisma.CarritosUncheckedUpdateOneWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUncheckedUpdateManyWithoutCompradorNestedInput
}

export type CompradoresCreateManyInput = {
  usuario_id: number
}

export type CompradoresUpdateManyMutationInput = {

}

export type CompradoresUncheckedUpdateManyInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CompradoresCountOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type CompradoresAvgOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type CompradoresMaxOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type CompradoresMinOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type CompradoresSumOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type CompradoresScalarRelationFilter = {
  is?: Prisma.CompradoresWhereInput
  isNot?: Prisma.CompradoresWhereInput
}

export type CompradoresNullableScalarRelationFilter = {
  is?: Prisma.CompradoresWhereInput | null
  isNot?: Prisma.CompradoresWhereInput | null
}

export type CompradoresCreateNestedOneWithoutLibrosDigitalesAdquiridosInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutLibrosDigitalesAdquiridosInput
  connect?: Prisma.CompradoresWhereUniqueInput
}

export type CompradoresUpdateOneRequiredWithoutLibrosDigitalesAdquiridosNestedInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutLibrosDigitalesAdquiridosInput
  upsert?: Prisma.CompradoresUpsertWithoutLibrosDigitalesAdquiridosInput
  connect?: Prisma.CompradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompradoresUpdateToOneWithWhereWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUpdateWithoutLibrosDigitalesAdquiridosInput>, Prisma.CompradoresUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput>
}

export type CompradoresCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutUsuariosInput, Prisma.CompradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.CompradoresWhereUniqueInput
}

export type CompradoresUncheckedCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutUsuariosInput, Prisma.CompradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.CompradoresWhereUniqueInput
}

export type CompradoresUpdateOneWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutUsuariosInput, Prisma.CompradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.CompradoresUpsertWithoutUsuariosInput
  disconnect?: Prisma.CompradoresWhereInput | boolean
  delete?: Prisma.CompradoresWhereInput | boolean
  connect?: Prisma.CompradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompradoresUpdateToOneWithWhereWithoutUsuariosInput, Prisma.CompradoresUpdateWithoutUsuariosInput>, Prisma.CompradoresUncheckedUpdateWithoutUsuariosInput>
}

export type CompradoresUncheckedUpdateOneWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutUsuariosInput, Prisma.CompradoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.CompradoresUpsertWithoutUsuariosInput
  disconnect?: Prisma.CompradoresWhereInput | boolean
  delete?: Prisma.CompradoresWhereInput | boolean
  connect?: Prisma.CompradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompradoresUpdateToOneWithWhereWithoutUsuariosInput, Prisma.CompradoresUpdateWithoutUsuariosInput>, Prisma.CompradoresUncheckedUpdateWithoutUsuariosInput>
}

export type CompradoresCreateNestedOneWithoutCarritoInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutCarritoInput, Prisma.CompradoresUncheckedCreateWithoutCarritoInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutCarritoInput
  connect?: Prisma.CompradoresWhereUniqueInput
}

export type CompradoresUpdateOneRequiredWithoutCarritoNestedInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutCarritoInput, Prisma.CompradoresUncheckedCreateWithoutCarritoInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutCarritoInput
  upsert?: Prisma.CompradoresUpsertWithoutCarritoInput
  connect?: Prisma.CompradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompradoresUpdateToOneWithWhereWithoutCarritoInput, Prisma.CompradoresUpdateWithoutCarritoInput>, Prisma.CompradoresUncheckedUpdateWithoutCarritoInput>
}

export type CompradoresCreateNestedOneWithoutTransaccionesInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutTransaccionesInput, Prisma.CompradoresUncheckedCreateWithoutTransaccionesInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutTransaccionesInput
  connect?: Prisma.CompradoresWhereUniqueInput
}

export type CompradoresUpdateOneRequiredWithoutTransaccionesNestedInput = {
  create?: Prisma.XOR<Prisma.CompradoresCreateWithoutTransaccionesInput, Prisma.CompradoresUncheckedCreateWithoutTransaccionesInput>
  connectOrCreate?: Prisma.CompradoresCreateOrConnectWithoutTransaccionesInput
  upsert?: Prisma.CompradoresUpsertWithoutTransaccionesInput
  connect?: Prisma.CompradoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompradoresUpdateToOneWithWhereWithoutTransaccionesInput, Prisma.CompradoresUpdateWithoutTransaccionesInput>, Prisma.CompradoresUncheckedUpdateWithoutTransaccionesInput>
}

export type CompradoresCreateWithoutLibrosDigitalesAdquiridosInput = {
  Carrito?: Prisma.CarritosCreateNestedOneWithoutCompradoresInput
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesCreateNestedManyWithoutCompradorInput
}

export type CompradoresUncheckedCreateWithoutLibrosDigitalesAdquiridosInput = {
  usuario_id: number
  Carrito?: Prisma.CarritosUncheckedCreateNestedOneWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesUncheckedCreateNestedManyWithoutCompradorInput
}

export type CompradoresCreateOrConnectWithoutLibrosDigitalesAdquiridosInput = {
  where: Prisma.CompradoresWhereUniqueInput
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
}

export type CompradoresUpsertWithoutLibrosDigitalesAdquiridosInput = {
  update: Prisma.XOR<Prisma.CompradoresUpdateWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput>
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
  where?: Prisma.CompradoresWhereInput
}

export type CompradoresUpdateToOneWithWhereWithoutLibrosDigitalesAdquiridosInput = {
  where?: Prisma.CompradoresWhereInput
  data: Prisma.XOR<Prisma.CompradoresUpdateWithoutLibrosDigitalesAdquiridosInput, Prisma.CompradoresUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput>
}

export type CompradoresUpdateWithoutLibrosDigitalesAdquiridosInput = {
  Carrito?: Prisma.CarritosUpdateOneWithoutCompradoresNestedInput
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUpdateManyWithoutCompradorNestedInput
}

export type CompradoresUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  Carrito?: Prisma.CarritosUncheckedUpdateOneWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUncheckedUpdateManyWithoutCompradorNestedInput
}

export type CompradoresCreateWithoutUsuariosInput = {
  Carrito?: Prisma.CarritosCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesCreateNestedManyWithoutCompradorInput
}

export type CompradoresUncheckedCreateWithoutUsuariosInput = {
  Carrito?: Prisma.CarritosUncheckedCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesUncheckedCreateNestedManyWithoutCompradorInput
}

export type CompradoresCreateOrConnectWithoutUsuariosInput = {
  where: Prisma.CompradoresWhereUniqueInput
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutUsuariosInput, Prisma.CompradoresUncheckedCreateWithoutUsuariosInput>
}

export type CompradoresUpsertWithoutUsuariosInput = {
  update: Prisma.XOR<Prisma.CompradoresUpdateWithoutUsuariosInput, Prisma.CompradoresUncheckedUpdateWithoutUsuariosInput>
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutUsuariosInput, Prisma.CompradoresUncheckedCreateWithoutUsuariosInput>
  where?: Prisma.CompradoresWhereInput
}

export type CompradoresUpdateToOneWithWhereWithoutUsuariosInput = {
  where?: Prisma.CompradoresWhereInput
  data: Prisma.XOR<Prisma.CompradoresUpdateWithoutUsuariosInput, Prisma.CompradoresUncheckedUpdateWithoutUsuariosInput>
}

export type CompradoresUpdateWithoutUsuariosInput = {
  Carrito?: Prisma.CarritosUpdateOneWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUpdateManyWithoutCompradorNestedInput
}

export type CompradoresUncheckedUpdateWithoutUsuariosInput = {
  Carrito?: Prisma.CarritosUncheckedUpdateOneWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUncheckedUpdateManyWithoutCompradorNestedInput
}

export type CompradoresCreateWithoutCarritoInput = {
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesCreateNestedManyWithoutCompradorInput
}

export type CompradoresUncheckedCreateWithoutCarritoInput = {
  usuario_id: number
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutCompradoresInput
  transacciones?: Prisma.TransaccionesUncheckedCreateNestedManyWithoutCompradorInput
}

export type CompradoresCreateOrConnectWithoutCarritoInput = {
  where: Prisma.CompradoresWhereUniqueInput
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutCarritoInput, Prisma.CompradoresUncheckedCreateWithoutCarritoInput>
}

export type CompradoresUpsertWithoutCarritoInput = {
  update: Prisma.XOR<Prisma.CompradoresUpdateWithoutCarritoInput, Prisma.CompradoresUncheckedUpdateWithoutCarritoInput>
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutCarritoInput, Prisma.CompradoresUncheckedCreateWithoutCarritoInput>
  where?: Prisma.CompradoresWhereInput
}

export type CompradoresUpdateToOneWithWhereWithoutCarritoInput = {
  where?: Prisma.CompradoresWhereInput
  data: Prisma.XOR<Prisma.CompradoresUpdateWithoutCarritoInput, Prisma.CompradoresUncheckedUpdateWithoutCarritoInput>
}

export type CompradoresUpdateWithoutCarritoInput = {
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUpdateManyWithoutCompradorNestedInput
}

export type CompradoresUncheckedUpdateWithoutCarritoInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutCompradoresNestedInput
  transacciones?: Prisma.TransaccionesUncheckedUpdateManyWithoutCompradorNestedInput
}

export type CompradoresCreateWithoutTransaccionesInput = {
  Carrito?: Prisma.CarritosCreateNestedOneWithoutCompradoresInput
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutCompradoresInput
}

export type CompradoresUncheckedCreateWithoutTransaccionesInput = {
  usuario_id: number
  Carrito?: Prisma.CarritosUncheckedCreateNestedOneWithoutCompradoresInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutCompradoresInput
}

export type CompradoresCreateOrConnectWithoutTransaccionesInput = {
  where: Prisma.CompradoresWhereUniqueInput
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutTransaccionesInput, Prisma.CompradoresUncheckedCreateWithoutTransaccionesInput>
}

export type CompradoresUpsertWithoutTransaccionesInput = {
  update: Prisma.XOR<Prisma.CompradoresUpdateWithoutTransaccionesInput, Prisma.CompradoresUncheckedUpdateWithoutTransaccionesInput>
  create: Prisma.XOR<Prisma.CompradoresCreateWithoutTransaccionesInput, Prisma.CompradoresUncheckedCreateWithoutTransaccionesInput>
  where?: Prisma.CompradoresWhereInput
}

export type CompradoresUpdateToOneWithWhereWithoutTransaccionesInput = {
  where?: Prisma.CompradoresWhereInput
  data: Prisma.XOR<Prisma.CompradoresUpdateWithoutTransaccionesInput, Prisma.CompradoresUncheckedUpdateWithoutTransaccionesInput>
}

export type CompradoresUpdateWithoutTransaccionesInput = {
  Carrito?: Prisma.CarritosUpdateOneWithoutCompradoresNestedInput
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutCompradoresNestedInput
}

export type CompradoresUncheckedUpdateWithoutTransaccionesInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  Carrito?: Prisma.CarritosUncheckedUpdateOneWithoutCompradoresNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutCompradoresNestedInput
}


/**
 * Count Type CompradoresCountOutputType
 */

export type CompradoresCountOutputType = {
  LibrosDigitalesAdquiridos: number
  transacciones: number
}

export type CompradoresCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  LibrosDigitalesAdquiridos?: boolean | CompradoresCountOutputTypeCountLibrosDigitalesAdquiridosArgs
  transacciones?: boolean | CompradoresCountOutputTypeCountTransaccionesArgs
}

/**
 * CompradoresCountOutputType without action
 */
export type CompradoresCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompradoresCountOutputType
   */
  select?: Prisma.CompradoresCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CompradoresCountOutputType without action
 */
export type CompradoresCountOutputTypeCountLibrosDigitalesAdquiridosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LibroDigitalAdquiridoWhereInput
}

/**
 * CompradoresCountOutputType without action
 */
export type CompradoresCountOutputTypeCountTransaccionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransaccionesWhereInput
}


export type CompradoresSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Carrito?: boolean | Prisma.Compradores$CarritoArgs<ExtArgs>
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
  LibrosDigitalesAdquiridos?: boolean | Prisma.Compradores$LibrosDigitalesAdquiridosArgs<ExtArgs>
  transacciones?: boolean | Prisma.Compradores$transaccionesArgs<ExtArgs>
  _count?: boolean | Prisma.CompradoresCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["compradores"]>

export type CompradoresSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["compradores"]>

export type CompradoresSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["compradores"]>

export type CompradoresSelectScalar = {
  usuario_id?: boolean
}

export type CompradoresOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"usuario_id", ExtArgs["result"]["compradores"]>
export type CompradoresInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Carrito?: boolean | Prisma.Compradores$CarritoArgs<ExtArgs>
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
  LibrosDigitalesAdquiridos?: boolean | Prisma.Compradores$LibrosDigitalesAdquiridosArgs<ExtArgs>
  transacciones?: boolean | Prisma.Compradores$transaccionesArgs<ExtArgs>
  _count?: boolean | Prisma.CompradoresCountOutputTypeDefaultArgs<ExtArgs>
}
export type CompradoresIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type CompradoresIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}

export type $CompradoresPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Compradores"
  objects: {
    Carrito: Prisma.$CarritosPayload<ExtArgs> | null
    Usuarios: Prisma.$UsuariosPayload<ExtArgs>
    LibrosDigitalesAdquiridos: Prisma.$LibroDigitalAdquiridoPayload<ExtArgs>[]
    transacciones: Prisma.$TransaccionesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    usuario_id: number
  }, ExtArgs["result"]["compradores"]>
  composites: {}
}

export type CompradoresGetPayload<S extends boolean | null | undefined | CompradoresDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CompradoresPayload, S>

export type CompradoresCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CompradoresFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CompradoresCountAggregateInputType | true
  }

export interface CompradoresDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Compradores'], meta: { name: 'Compradores' } }
  /**
   * Find zero or one Compradores that matches the filter.
   * @param {CompradoresFindUniqueArgs} args - Arguments to find a Compradores
   * @example
   * // Get one Compradores
   * const compradores = await prisma.compradores.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CompradoresFindUniqueArgs>(args: Prisma.SelectSubset<T, CompradoresFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Compradores that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CompradoresFindUniqueOrThrowArgs} args - Arguments to find a Compradores
   * @example
   * // Get one Compradores
   * const compradores = await prisma.compradores.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CompradoresFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CompradoresFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Compradores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresFindFirstArgs} args - Arguments to find a Compradores
   * @example
   * // Get one Compradores
   * const compradores = await prisma.compradores.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CompradoresFindFirstArgs>(args?: Prisma.SelectSubset<T, CompradoresFindFirstArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Compradores that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresFindFirstOrThrowArgs} args - Arguments to find a Compradores
   * @example
   * // Get one Compradores
   * const compradores = await prisma.compradores.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CompradoresFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CompradoresFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Compradores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Compradores
   * const compradores = await prisma.compradores.findMany()
   * 
   * // Get first 10 Compradores
   * const compradores = await prisma.compradores.findMany({ take: 10 })
   * 
   * // Only select the `usuario_id`
   * const compradoresWithUsuario_idOnly = await prisma.compradores.findMany({ select: { usuario_id: true } })
   * 
   */
  findMany<T extends CompradoresFindManyArgs>(args?: Prisma.SelectSubset<T, CompradoresFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Compradores.
   * @param {CompradoresCreateArgs} args - Arguments to create a Compradores.
   * @example
   * // Create one Compradores
   * const Compradores = await prisma.compradores.create({
   *   data: {
   *     // ... data to create a Compradores
   *   }
   * })
   * 
   */
  create<T extends CompradoresCreateArgs>(args: Prisma.SelectSubset<T, CompradoresCreateArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Compradores.
   * @param {CompradoresCreateManyArgs} args - Arguments to create many Compradores.
   * @example
   * // Create many Compradores
   * const compradores = await prisma.compradores.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CompradoresCreateManyArgs>(args?: Prisma.SelectSubset<T, CompradoresCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Compradores and returns the data saved in the database.
   * @param {CompradoresCreateManyAndReturnArgs} args - Arguments to create many Compradores.
   * @example
   * // Create many Compradores
   * const compradores = await prisma.compradores.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Compradores and only return the `usuario_id`
   * const compradoresWithUsuario_idOnly = await prisma.compradores.createManyAndReturn({
   *   select: { usuario_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CompradoresCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CompradoresCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Compradores.
   * @param {CompradoresDeleteArgs} args - Arguments to delete one Compradores.
   * @example
   * // Delete one Compradores
   * const Compradores = await prisma.compradores.delete({
   *   where: {
   *     // ... filter to delete one Compradores
   *   }
   * })
   * 
   */
  delete<T extends CompradoresDeleteArgs>(args: Prisma.SelectSubset<T, CompradoresDeleteArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Compradores.
   * @param {CompradoresUpdateArgs} args - Arguments to update one Compradores.
   * @example
   * // Update one Compradores
   * const compradores = await prisma.compradores.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CompradoresUpdateArgs>(args: Prisma.SelectSubset<T, CompradoresUpdateArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Compradores.
   * @param {CompradoresDeleteManyArgs} args - Arguments to filter Compradores to delete.
   * @example
   * // Delete a few Compradores
   * const { count } = await prisma.compradores.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CompradoresDeleteManyArgs>(args?: Prisma.SelectSubset<T, CompradoresDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Compradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Compradores
   * const compradores = await prisma.compradores.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CompradoresUpdateManyArgs>(args: Prisma.SelectSubset<T, CompradoresUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Compradores and returns the data updated in the database.
   * @param {CompradoresUpdateManyAndReturnArgs} args - Arguments to update many Compradores.
   * @example
   * // Update many Compradores
   * const compradores = await prisma.compradores.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Compradores and only return the `usuario_id`
   * const compradoresWithUsuario_idOnly = await prisma.compradores.updateManyAndReturn({
   *   select: { usuario_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CompradoresUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CompradoresUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Compradores.
   * @param {CompradoresUpsertArgs} args - Arguments to update or create a Compradores.
   * @example
   * // Update or create a Compradores
   * const compradores = await prisma.compradores.upsert({
   *   create: {
   *     // ... data to create a Compradores
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Compradores we want to update
   *   }
   * })
   */
  upsert<T extends CompradoresUpsertArgs>(args: Prisma.SelectSubset<T, CompradoresUpsertArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Compradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresCountArgs} args - Arguments to filter Compradores to count.
   * @example
   * // Count the number of Compradores
   * const count = await prisma.compradores.count({
   *   where: {
   *     // ... the filter for the Compradores we want to count
   *   }
   * })
  **/
  count<T extends CompradoresCountArgs>(
    args?: Prisma.Subset<T, CompradoresCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CompradoresCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Compradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CompradoresAggregateArgs>(args: Prisma.Subset<T, CompradoresAggregateArgs>): Prisma.PrismaPromise<GetCompradoresAggregateType<T>>

  /**
   * Group by Compradores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompradoresGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CompradoresGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CompradoresGroupByArgs['orderBy'] }
      : { orderBy?: CompradoresGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CompradoresGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCompradoresGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Compradores model
 */
readonly fields: CompradoresFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Compradores.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CompradoresClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Carrito<T extends Prisma.Compradores$CarritoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Compradores$CarritoArgs<ExtArgs>>): Prisma.Prisma__CarritosClient<runtime.Types.Result.GetResult<Prisma.$CarritosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  Usuarios<T extends Prisma.UsuariosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuariosDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  LibrosDigitalesAdquiridos<T extends Prisma.Compradores$LibrosDigitalesAdquiridosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Compradores$LibrosDigitalesAdquiridosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibroDigitalAdquiridoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  transacciones<T extends Prisma.Compradores$transaccionesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Compradores$transaccionesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaccionesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Compradores model
 */
export interface CompradoresFieldRefs {
  readonly usuario_id: Prisma.FieldRef<"Compradores", 'Int'>
}
    

// Custom InputTypes
/**
 * Compradores findUnique
 */
export type CompradoresFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * Filter, which Compradores to fetch.
   */
  where: Prisma.CompradoresWhereUniqueInput
}

/**
 * Compradores findUniqueOrThrow
 */
export type CompradoresFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * Filter, which Compradores to fetch.
   */
  where: Prisma.CompradoresWhereUniqueInput
}

/**
 * Compradores findFirst
 */
export type CompradoresFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * Filter, which Compradores to fetch.
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Compradores to fetch.
   */
  orderBy?: Prisma.CompradoresOrderByWithRelationInput | Prisma.CompradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Compradores.
   */
  cursor?: Prisma.CompradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Compradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Compradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Compradores.
   */
  distinct?: Prisma.CompradoresScalarFieldEnum | Prisma.CompradoresScalarFieldEnum[]
}

/**
 * Compradores findFirstOrThrow
 */
export type CompradoresFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * Filter, which Compradores to fetch.
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Compradores to fetch.
   */
  orderBy?: Prisma.CompradoresOrderByWithRelationInput | Prisma.CompradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Compradores.
   */
  cursor?: Prisma.CompradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Compradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Compradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Compradores.
   */
  distinct?: Prisma.CompradoresScalarFieldEnum | Prisma.CompradoresScalarFieldEnum[]
}

/**
 * Compradores findMany
 */
export type CompradoresFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * Filter, which Compradores to fetch.
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Compradores to fetch.
   */
  orderBy?: Prisma.CompradoresOrderByWithRelationInput | Prisma.CompradoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Compradores.
   */
  cursor?: Prisma.CompradoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Compradores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Compradores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Compradores.
   */
  distinct?: Prisma.CompradoresScalarFieldEnum | Prisma.CompradoresScalarFieldEnum[]
}

/**
 * Compradores create
 */
export type CompradoresCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * The data needed to create a Compradores.
   */
  data: Prisma.XOR<Prisma.CompradoresCreateInput, Prisma.CompradoresUncheckedCreateInput>
}

/**
 * Compradores createMany
 */
export type CompradoresCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Compradores.
   */
  data: Prisma.CompradoresCreateManyInput | Prisma.CompradoresCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Compradores createManyAndReturn
 */
export type CompradoresCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * The data used to create many Compradores.
   */
  data: Prisma.CompradoresCreateManyInput | Prisma.CompradoresCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Compradores update
 */
export type CompradoresUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * The data needed to update a Compradores.
   */
  data: Prisma.XOR<Prisma.CompradoresUpdateInput, Prisma.CompradoresUncheckedUpdateInput>
  /**
   * Choose, which Compradores to update.
   */
  where: Prisma.CompradoresWhereUniqueInput
}

/**
 * Compradores updateMany
 */
export type CompradoresUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Compradores.
   */
  data: Prisma.XOR<Prisma.CompradoresUpdateManyMutationInput, Prisma.CompradoresUncheckedUpdateManyInput>
  /**
   * Filter which Compradores to update
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * Limit how many Compradores to update.
   */
  limit?: number
}

/**
 * Compradores updateManyAndReturn
 */
export type CompradoresUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * The data used to update Compradores.
   */
  data: Prisma.XOR<Prisma.CompradoresUpdateManyMutationInput, Prisma.CompradoresUncheckedUpdateManyInput>
  /**
   * Filter which Compradores to update
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * Limit how many Compradores to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Compradores upsert
 */
export type CompradoresUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * The filter to search for the Compradores to update in case it exists.
   */
  where: Prisma.CompradoresWhereUniqueInput
  /**
   * In case the Compradores found by the `where` argument doesn't exist, create a new Compradores with this data.
   */
  create: Prisma.XOR<Prisma.CompradoresCreateInput, Prisma.CompradoresUncheckedCreateInput>
  /**
   * In case the Compradores was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CompradoresUpdateInput, Prisma.CompradoresUncheckedUpdateInput>
}

/**
 * Compradores delete
 */
export type CompradoresDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
  /**
   * Filter which Compradores to delete.
   */
  where: Prisma.CompradoresWhereUniqueInput
}

/**
 * Compradores deleteMany
 */
export type CompradoresDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Compradores to delete
   */
  where?: Prisma.CompradoresWhereInput
  /**
   * Limit how many Compradores to delete.
   */
  limit?: number
}

/**
 * Compradores.Carrito
 */
export type Compradores$CarritoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carritos
   */
  select?: Prisma.CarritosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carritos
   */
  omit?: Prisma.CarritosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarritosInclude<ExtArgs> | null
  where?: Prisma.CarritosWhereInput
}

/**
 * Compradores.LibrosDigitalesAdquiridos
 */
export type Compradores$LibrosDigitalesAdquiridosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibroDigitalAdquirido
   */
  select?: Prisma.LibroDigitalAdquiridoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibroDigitalAdquirido
   */
  omit?: Prisma.LibroDigitalAdquiridoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibroDigitalAdquiridoInclude<ExtArgs> | null
  where?: Prisma.LibroDigitalAdquiridoWhereInput
  orderBy?: Prisma.LibroDigitalAdquiridoOrderByWithRelationInput | Prisma.LibroDigitalAdquiridoOrderByWithRelationInput[]
  cursor?: Prisma.LibroDigitalAdquiridoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LibroDigitalAdquiridoScalarFieldEnum | Prisma.LibroDigitalAdquiridoScalarFieldEnum[]
}

/**
 * Compradores.transacciones
 */
export type Compradores$transaccionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transacciones
   */
  select?: Prisma.TransaccionesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transacciones
   */
  omit?: Prisma.TransaccionesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaccionesInclude<ExtArgs> | null
  where?: Prisma.TransaccionesWhereInput
  orderBy?: Prisma.TransaccionesOrderByWithRelationInput | Prisma.TransaccionesOrderByWithRelationInput[]
  cursor?: Prisma.TransaccionesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransaccionesScalarFieldEnum | Prisma.TransaccionesScalarFieldEnum[]
}

/**
 * Compradores without action
 */
export type CompradoresDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Compradores
   */
  select?: Prisma.CompradoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Compradores
   */
  omit?: Prisma.CompradoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompradoresInclude<ExtArgs> | null
}
