
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DetallesCarrito` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DetallesCarrito
 * 
 */
export type DetallesCarritoModel = runtime.Types.Result.DefaultSelection<Prisma.$DetallesCarritoPayload>

export type AggregateDetallesCarrito = {
  _count: DetallesCarritoCountAggregateOutputType | null
  _avg: DetallesCarritoAvgAggregateOutputType | null
  _sum: DetallesCarritoSumAggregateOutputType | null
  _min: DetallesCarritoMinAggregateOutputType | null
  _max: DetallesCarritoMaxAggregateOutputType | null
}

export type DetallesCarritoAvgAggregateOutputType = {
  id: number | null
  carrito_id: number | null
  libro_id: number | null
  cantidad: number | null
  precio: runtime.Decimal | null
}

export type DetallesCarritoSumAggregateOutputType = {
  id: number | null
  carrito_id: number | null
  libro_id: number | null
  cantidad: number | null
  precio: runtime.Decimal | null
}

export type DetallesCarritoMinAggregateOutputType = {
  id: number | null
  carrito_id: number | null
  libro_id: number | null
  cantidad: number | null
  precio: runtime.Decimal | null
  es_digital: boolean | null
}

export type DetallesCarritoMaxAggregateOutputType = {
  id: number | null
  carrito_id: number | null
  libro_id: number | null
  cantidad: number | null
  precio: runtime.Decimal | null
  es_digital: boolean | null
}

export type DetallesCarritoCountAggregateOutputType = {
  id: number
  carrito_id: number
  libro_id: number
  cantidad: number
  precio: number
  es_digital: number
  _all: number
}


export type DetallesCarritoAvgAggregateInputType = {
  id?: true
  carrito_id?: true
  libro_id?: true
  cantidad?: true
  precio?: true
}

export type DetallesCarritoSumAggregateInputType = {
  id?: true
  carrito_id?: true
  libro_id?: true
  cantidad?: true
  precio?: true
}

export type DetallesCarritoMinAggregateInputType = {
  id?: true
  carrito_id?: true
  libro_id?: true
  cantidad?: true
  precio?: true
  es_digital?: true
}

export type DetallesCarritoMaxAggregateInputType = {
  id?: true
  carrito_id?: true
  libro_id?: true
  cantidad?: true
  precio?: true
  es_digital?: true
}

export type DetallesCarritoCountAggregateInputType = {
  id?: true
  carrito_id?: true
  libro_id?: true
  cantidad?: true
  precio?: true
  es_digital?: true
  _all?: true
}

export type DetallesCarritoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DetallesCarrito to aggregate.
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DetallesCarritos to fetch.
   */
  orderBy?: Prisma.DetallesCarritoOrderByWithRelationInput | Prisma.DetallesCarritoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DetallesCarritoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DetallesCarritos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DetallesCarritos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DetallesCarritos
  **/
  _count?: true | DetallesCarritoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DetallesCarritoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DetallesCarritoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DetallesCarritoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DetallesCarritoMaxAggregateInputType
}

export type GetDetallesCarritoAggregateType<T extends DetallesCarritoAggregateArgs> = {
      [P in keyof T & keyof AggregateDetallesCarrito]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDetallesCarrito[P]>
    : Prisma.GetScalarType<T[P], AggregateDetallesCarrito[P]>
}




export type DetallesCarritoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DetallesCarritoWhereInput
  orderBy?: Prisma.DetallesCarritoOrderByWithAggregationInput | Prisma.DetallesCarritoOrderByWithAggregationInput[]
  by: Prisma.DetallesCarritoScalarFieldEnum[] | Prisma.DetallesCarritoScalarFieldEnum
  having?: Prisma.DetallesCarritoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DetallesCarritoCountAggregateInputType | true
  _avg?: DetallesCarritoAvgAggregateInputType
  _sum?: DetallesCarritoSumAggregateInputType
  _min?: DetallesCarritoMinAggregateInputType
  _max?: DetallesCarritoMaxAggregateInputType
}

export type DetallesCarritoGroupByOutputType = {
  id: number
  carrito_id: number
  libro_id: number
  cantidad: number
  precio: runtime.Decimal
  es_digital: boolean
  _count: DetallesCarritoCountAggregateOutputType | null
  _avg: DetallesCarritoAvgAggregateOutputType | null
  _sum: DetallesCarritoSumAggregateOutputType | null
  _min: DetallesCarritoMinAggregateOutputType | null
  _max: DetallesCarritoMaxAggregateOutputType | null
}

export type GetDetallesCarritoGroupByPayload<T extends DetallesCarritoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DetallesCarritoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DetallesCarritoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DetallesCarritoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DetallesCarritoGroupByOutputType[P]>
      }
    >
  >



export type DetallesCarritoWhereInput = {
  AND?: Prisma.DetallesCarritoWhereInput | Prisma.DetallesCarritoWhereInput[]
  OR?: Prisma.DetallesCarritoWhereInput[]
  NOT?: Prisma.DetallesCarritoWhereInput | Prisma.DetallesCarritoWhereInput[]
  id?: Prisma.IntFilter<"DetallesCarrito"> | number
  carrito_id?: Prisma.IntFilter<"DetallesCarrito"> | number
  libro_id?: Prisma.IntFilter<"DetallesCarrito"> | number
  cantidad?: Prisma.IntFilter<"DetallesCarrito"> | number
  precio?: Prisma.DecimalFilter<"DetallesCarrito"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFilter<"DetallesCarrito"> | boolean
  Carrito?: Prisma.XOR<Prisma.CarritosScalarRelationFilter, Prisma.CarritosWhereInput>
  Libros?: Prisma.XOR<Prisma.LibrosScalarRelationFilter, Prisma.LibrosWhereInput>
}

export type DetallesCarritoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  es_digital?: Prisma.SortOrder
  Carrito?: Prisma.CarritosOrderByWithRelationInput
  Libros?: Prisma.LibrosOrderByWithRelationInput
}

export type DetallesCarritoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  carrito_id_libro_id_es_digital?: Prisma.DetallesCarritoCarrito_idLibro_idEs_digitalCompoundUniqueInput
  AND?: Prisma.DetallesCarritoWhereInput | Prisma.DetallesCarritoWhereInput[]
  OR?: Prisma.DetallesCarritoWhereInput[]
  NOT?: Prisma.DetallesCarritoWhereInput | Prisma.DetallesCarritoWhereInput[]
  carrito_id?: Prisma.IntFilter<"DetallesCarrito"> | number
  libro_id?: Prisma.IntFilter<"DetallesCarrito"> | number
  cantidad?: Prisma.IntFilter<"DetallesCarrito"> | number
  precio?: Prisma.DecimalFilter<"DetallesCarrito"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFilter<"DetallesCarrito"> | boolean
  Carrito?: Prisma.XOR<Prisma.CarritosScalarRelationFilter, Prisma.CarritosWhereInput>
  Libros?: Prisma.XOR<Prisma.LibrosScalarRelationFilter, Prisma.LibrosWhereInput>
}, "id" | "carrito_id_libro_id_es_digital">

export type DetallesCarritoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  es_digital?: Prisma.SortOrder
  _count?: Prisma.DetallesCarritoCountOrderByAggregateInput
  _avg?: Prisma.DetallesCarritoAvgOrderByAggregateInput
  _max?: Prisma.DetallesCarritoMaxOrderByAggregateInput
  _min?: Prisma.DetallesCarritoMinOrderByAggregateInput
  _sum?: Prisma.DetallesCarritoSumOrderByAggregateInput
}

export type DetallesCarritoScalarWhereWithAggregatesInput = {
  AND?: Prisma.DetallesCarritoScalarWhereWithAggregatesInput | Prisma.DetallesCarritoScalarWhereWithAggregatesInput[]
  OR?: Prisma.DetallesCarritoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DetallesCarritoScalarWhereWithAggregatesInput | Prisma.DetallesCarritoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DetallesCarrito"> | number
  carrito_id?: Prisma.IntWithAggregatesFilter<"DetallesCarrito"> | number
  libro_id?: Prisma.IntWithAggregatesFilter<"DetallesCarrito"> | number
  cantidad?: Prisma.IntWithAggregatesFilter<"DetallesCarrito"> | number
  precio?: Prisma.DecimalWithAggregatesFilter<"DetallesCarrito"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolWithAggregatesFilter<"DetallesCarrito"> | boolean
}

export type DetallesCarritoCreateInput = {
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
  Carrito: Prisma.CarritosCreateNestedOneWithoutDetallesInput
  Libros: Prisma.LibrosCreateNestedOneWithoutDetallesCarritosInput
}

export type DetallesCarritoUncheckedCreateInput = {
  id?: number
  carrito_id: number
  libro_id: number
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
}

export type DetallesCarritoUpdateInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Carrito?: Prisma.CarritosUpdateOneRequiredWithoutDetallesNestedInput
  Libros?: Prisma.LibrosUpdateOneRequiredWithoutDetallesCarritosNestedInput
}

export type DetallesCarritoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrito_id?: Prisma.IntFieldUpdateOperationsInput | number
  libro_id?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DetallesCarritoCreateManyInput = {
  id?: number
  carrito_id: number
  libro_id: number
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
}

export type DetallesCarritoUpdateManyMutationInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DetallesCarritoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrito_id?: Prisma.IntFieldUpdateOperationsInput | number
  libro_id?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DetallesCarritoListRelationFilter = {
  every?: Prisma.DetallesCarritoWhereInput
  some?: Prisma.DetallesCarritoWhereInput
  none?: Prisma.DetallesCarritoWhereInput
}

export type DetallesCarritoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DetallesCarritoCarrito_idLibro_idEs_digitalCompoundUniqueInput = {
  carrito_id: number
  libro_id: number
  es_digital: boolean
}

export type DetallesCarritoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  es_digital?: Prisma.SortOrder
}

export type DetallesCarritoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
}

export type DetallesCarritoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  es_digital?: Prisma.SortOrder
}

export type DetallesCarritoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  es_digital?: Prisma.SortOrder
}

export type DetallesCarritoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrito_id?: Prisma.SortOrder
  libro_id?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  precio?: Prisma.SortOrder
}

export type DetallesCarritoCreateNestedManyWithoutLibrosInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput> | Prisma.DetallesCarritoCreateWithoutLibrosInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput | Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput[]
  createMany?: Prisma.DetallesCarritoCreateManyLibrosInputEnvelope
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
}

export type DetallesCarritoUncheckedCreateNestedManyWithoutLibrosInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput> | Prisma.DetallesCarritoCreateWithoutLibrosInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput | Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput[]
  createMany?: Prisma.DetallesCarritoCreateManyLibrosInputEnvelope
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
}

export type DetallesCarritoUpdateManyWithoutLibrosNestedInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput> | Prisma.DetallesCarritoCreateWithoutLibrosInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput | Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput[]
  upsert?: Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutLibrosInput | Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutLibrosInput[]
  createMany?: Prisma.DetallesCarritoCreateManyLibrosInputEnvelope
  set?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  disconnect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  delete?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  update?: Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutLibrosInput | Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutLibrosInput[]
  updateMany?: Prisma.DetallesCarritoUpdateManyWithWhereWithoutLibrosInput | Prisma.DetallesCarritoUpdateManyWithWhereWithoutLibrosInput[]
  deleteMany?: Prisma.DetallesCarritoScalarWhereInput | Prisma.DetallesCarritoScalarWhereInput[]
}

export type DetallesCarritoUncheckedUpdateManyWithoutLibrosNestedInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput> | Prisma.DetallesCarritoCreateWithoutLibrosInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput | Prisma.DetallesCarritoCreateOrConnectWithoutLibrosInput[]
  upsert?: Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutLibrosInput | Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutLibrosInput[]
  createMany?: Prisma.DetallesCarritoCreateManyLibrosInputEnvelope
  set?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  disconnect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  delete?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  update?: Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutLibrosInput | Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutLibrosInput[]
  updateMany?: Prisma.DetallesCarritoUpdateManyWithWhereWithoutLibrosInput | Prisma.DetallesCarritoUpdateManyWithWhereWithoutLibrosInput[]
  deleteMany?: Prisma.DetallesCarritoScalarWhereInput | Prisma.DetallesCarritoScalarWhereInput[]
}

export type DetallesCarritoCreateNestedManyWithoutCarritoInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput> | Prisma.DetallesCarritoCreateWithoutCarritoInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput | Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput[]
  createMany?: Prisma.DetallesCarritoCreateManyCarritoInputEnvelope
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
}

export type DetallesCarritoUncheckedCreateNestedManyWithoutCarritoInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput> | Prisma.DetallesCarritoCreateWithoutCarritoInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput | Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput[]
  createMany?: Prisma.DetallesCarritoCreateManyCarritoInputEnvelope
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
}

export type DetallesCarritoUpdateManyWithoutCarritoNestedInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput> | Prisma.DetallesCarritoCreateWithoutCarritoInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput | Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput[]
  upsert?: Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutCarritoInput | Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutCarritoInput[]
  createMany?: Prisma.DetallesCarritoCreateManyCarritoInputEnvelope
  set?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  disconnect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  delete?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  update?: Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutCarritoInput | Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutCarritoInput[]
  updateMany?: Prisma.DetallesCarritoUpdateManyWithWhereWithoutCarritoInput | Prisma.DetallesCarritoUpdateManyWithWhereWithoutCarritoInput[]
  deleteMany?: Prisma.DetallesCarritoScalarWhereInput | Prisma.DetallesCarritoScalarWhereInput[]
}

export type DetallesCarritoUncheckedUpdateManyWithoutCarritoNestedInput = {
  create?: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput> | Prisma.DetallesCarritoCreateWithoutCarritoInput[] | Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput[]
  connectOrCreate?: Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput | Prisma.DetallesCarritoCreateOrConnectWithoutCarritoInput[]
  upsert?: Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutCarritoInput | Prisma.DetallesCarritoUpsertWithWhereUniqueWithoutCarritoInput[]
  createMany?: Prisma.DetallesCarritoCreateManyCarritoInputEnvelope
  set?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  disconnect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  delete?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  connect?: Prisma.DetallesCarritoWhereUniqueInput | Prisma.DetallesCarritoWhereUniqueInput[]
  update?: Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutCarritoInput | Prisma.DetallesCarritoUpdateWithWhereUniqueWithoutCarritoInput[]
  updateMany?: Prisma.DetallesCarritoUpdateManyWithWhereWithoutCarritoInput | Prisma.DetallesCarritoUpdateManyWithWhereWithoutCarritoInput[]
  deleteMany?: Prisma.DetallesCarritoScalarWhereInput | Prisma.DetallesCarritoScalarWhereInput[]
}

export type DetallesCarritoCreateWithoutLibrosInput = {
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
  Carrito: Prisma.CarritosCreateNestedOneWithoutDetallesInput
}

export type DetallesCarritoUncheckedCreateWithoutLibrosInput = {
  id?: number
  carrito_id: number
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
}

export type DetallesCarritoCreateOrConnectWithoutLibrosInput = {
  where: Prisma.DetallesCarritoWhereUniqueInput
  create: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput>
}

export type DetallesCarritoCreateManyLibrosInputEnvelope = {
  data: Prisma.DetallesCarritoCreateManyLibrosInput | Prisma.DetallesCarritoCreateManyLibrosInput[]
  skipDuplicates?: boolean
}

export type DetallesCarritoUpsertWithWhereUniqueWithoutLibrosInput = {
  where: Prisma.DetallesCarritoWhereUniqueInput
  update: Prisma.XOR<Prisma.DetallesCarritoUpdateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedUpdateWithoutLibrosInput>
  create: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedCreateWithoutLibrosInput>
}

export type DetallesCarritoUpdateWithWhereUniqueWithoutLibrosInput = {
  where: Prisma.DetallesCarritoWhereUniqueInput
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateWithoutLibrosInput, Prisma.DetallesCarritoUncheckedUpdateWithoutLibrosInput>
}

export type DetallesCarritoUpdateManyWithWhereWithoutLibrosInput = {
  where: Prisma.DetallesCarritoScalarWhereInput
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateManyMutationInput, Prisma.DetallesCarritoUncheckedUpdateManyWithoutLibrosInput>
}

export type DetallesCarritoScalarWhereInput = {
  AND?: Prisma.DetallesCarritoScalarWhereInput | Prisma.DetallesCarritoScalarWhereInput[]
  OR?: Prisma.DetallesCarritoScalarWhereInput[]
  NOT?: Prisma.DetallesCarritoScalarWhereInput | Prisma.DetallesCarritoScalarWhereInput[]
  id?: Prisma.IntFilter<"DetallesCarrito"> | number
  carrito_id?: Prisma.IntFilter<"DetallesCarrito"> | number
  libro_id?: Prisma.IntFilter<"DetallesCarrito"> | number
  cantidad?: Prisma.IntFilter<"DetallesCarrito"> | number
  precio?: Prisma.DecimalFilter<"DetallesCarrito"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFilter<"DetallesCarrito"> | boolean
}

export type DetallesCarritoCreateWithoutCarritoInput = {
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
  Libros: Prisma.LibrosCreateNestedOneWithoutDetallesCarritosInput
}

export type DetallesCarritoUncheckedCreateWithoutCarritoInput = {
  id?: number
  libro_id: number
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
}

export type DetallesCarritoCreateOrConnectWithoutCarritoInput = {
  where: Prisma.DetallesCarritoWhereUniqueInput
  create: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput>
}

export type DetallesCarritoCreateManyCarritoInputEnvelope = {
  data: Prisma.DetallesCarritoCreateManyCarritoInput | Prisma.DetallesCarritoCreateManyCarritoInput[]
  skipDuplicates?: boolean
}

export type DetallesCarritoUpsertWithWhereUniqueWithoutCarritoInput = {
  where: Prisma.DetallesCarritoWhereUniqueInput
  update: Prisma.XOR<Prisma.DetallesCarritoUpdateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedUpdateWithoutCarritoInput>
  create: Prisma.XOR<Prisma.DetallesCarritoCreateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedCreateWithoutCarritoInput>
}

export type DetallesCarritoUpdateWithWhereUniqueWithoutCarritoInput = {
  where: Prisma.DetallesCarritoWhereUniqueInput
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateWithoutCarritoInput, Prisma.DetallesCarritoUncheckedUpdateWithoutCarritoInput>
}

export type DetallesCarritoUpdateManyWithWhereWithoutCarritoInput = {
  where: Prisma.DetallesCarritoScalarWhereInput
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateManyMutationInput, Prisma.DetallesCarritoUncheckedUpdateManyWithoutCarritoInput>
}

export type DetallesCarritoCreateManyLibrosInput = {
  id?: number
  carrito_id: number
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
}

export type DetallesCarritoUpdateWithoutLibrosInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Carrito?: Prisma.CarritosUpdateOneRequiredWithoutDetallesNestedInput
}

export type DetallesCarritoUncheckedUpdateWithoutLibrosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrito_id?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DetallesCarritoUncheckedUpdateManyWithoutLibrosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrito_id?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DetallesCarritoCreateManyCarritoInput = {
  id?: number
  libro_id: number
  cantidad?: number
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: boolean
}

export type DetallesCarritoUpdateWithoutCarritoInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Libros?: Prisma.LibrosUpdateOneRequiredWithoutDetallesCarritosNestedInput
}

export type DetallesCarritoUncheckedUpdateWithoutCarritoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  libro_id?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DetallesCarritoUncheckedUpdateManyWithoutCarritoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  libro_id?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  es_digital?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type DetallesCarritoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  carrito_id?: boolean
  libro_id?: boolean
  cantidad?: boolean
  precio?: boolean
  es_digital?: boolean
  Carrito?: boolean | Prisma.CarritosDefaultArgs<ExtArgs>
  Libros?: boolean | Prisma.LibrosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["detallesCarrito"]>

export type DetallesCarritoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  carrito_id?: boolean
  libro_id?: boolean
  cantidad?: boolean
  precio?: boolean
  es_digital?: boolean
  Carrito?: boolean | Prisma.CarritosDefaultArgs<ExtArgs>
  Libros?: boolean | Prisma.LibrosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["detallesCarrito"]>

export type DetallesCarritoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  carrito_id?: boolean
  libro_id?: boolean
  cantidad?: boolean
  precio?: boolean
  es_digital?: boolean
  Carrito?: boolean | Prisma.CarritosDefaultArgs<ExtArgs>
  Libros?: boolean | Prisma.LibrosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["detallesCarrito"]>

export type DetallesCarritoSelectScalar = {
  id?: boolean
  carrito_id?: boolean
  libro_id?: boolean
  cantidad?: boolean
  precio?: boolean
  es_digital?: boolean
}

export type DetallesCarritoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "carrito_id" | "libro_id" | "cantidad" | "precio" | "es_digital", ExtArgs["result"]["detallesCarrito"]>
export type DetallesCarritoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Carrito?: boolean | Prisma.CarritosDefaultArgs<ExtArgs>
  Libros?: boolean | Prisma.LibrosDefaultArgs<ExtArgs>
}
export type DetallesCarritoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Carrito?: boolean | Prisma.CarritosDefaultArgs<ExtArgs>
  Libros?: boolean | Prisma.LibrosDefaultArgs<ExtArgs>
}
export type DetallesCarritoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Carrito?: boolean | Prisma.CarritosDefaultArgs<ExtArgs>
  Libros?: boolean | Prisma.LibrosDefaultArgs<ExtArgs>
}

export type $DetallesCarritoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DetallesCarrito"
  objects: {
    Carrito: Prisma.$CarritosPayload<ExtArgs>
    Libros: Prisma.$LibrosPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    carrito_id: number
    libro_id: number
    cantidad: number
    precio: runtime.Decimal
    es_digital: boolean
  }, ExtArgs["result"]["detallesCarrito"]>
  composites: {}
}

export type DetallesCarritoGetPayload<S extends boolean | null | undefined | DetallesCarritoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload, S>

export type DetallesCarritoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DetallesCarritoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DetallesCarritoCountAggregateInputType | true
  }

export interface DetallesCarritoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DetallesCarrito'], meta: { name: 'DetallesCarrito' } }
  /**
   * Find zero or one DetallesCarrito that matches the filter.
   * @param {DetallesCarritoFindUniqueArgs} args - Arguments to find a DetallesCarrito
   * @example
   * // Get one DetallesCarrito
   * const detallesCarrito = await prisma.detallesCarrito.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DetallesCarritoFindUniqueArgs>(args: Prisma.SelectSubset<T, DetallesCarritoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DetallesCarrito that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DetallesCarritoFindUniqueOrThrowArgs} args - Arguments to find a DetallesCarrito
   * @example
   * // Get one DetallesCarrito
   * const detallesCarrito = await prisma.detallesCarrito.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DetallesCarritoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DetallesCarritoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DetallesCarrito that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoFindFirstArgs} args - Arguments to find a DetallesCarrito
   * @example
   * // Get one DetallesCarrito
   * const detallesCarrito = await prisma.detallesCarrito.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DetallesCarritoFindFirstArgs>(args?: Prisma.SelectSubset<T, DetallesCarritoFindFirstArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DetallesCarrito that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoFindFirstOrThrowArgs} args - Arguments to find a DetallesCarrito
   * @example
   * // Get one DetallesCarrito
   * const detallesCarrito = await prisma.detallesCarrito.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DetallesCarritoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DetallesCarritoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DetallesCarritos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DetallesCarritos
   * const detallesCarritos = await prisma.detallesCarrito.findMany()
   * 
   * // Get first 10 DetallesCarritos
   * const detallesCarritos = await prisma.detallesCarrito.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const detallesCarritoWithIdOnly = await prisma.detallesCarrito.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DetallesCarritoFindManyArgs>(args?: Prisma.SelectSubset<T, DetallesCarritoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DetallesCarrito.
   * @param {DetallesCarritoCreateArgs} args - Arguments to create a DetallesCarrito.
   * @example
   * // Create one DetallesCarrito
   * const DetallesCarrito = await prisma.detallesCarrito.create({
   *   data: {
   *     // ... data to create a DetallesCarrito
   *   }
   * })
   * 
   */
  create<T extends DetallesCarritoCreateArgs>(args: Prisma.SelectSubset<T, DetallesCarritoCreateArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DetallesCarritos.
   * @param {DetallesCarritoCreateManyArgs} args - Arguments to create many DetallesCarritos.
   * @example
   * // Create many DetallesCarritos
   * const detallesCarrito = await prisma.detallesCarrito.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DetallesCarritoCreateManyArgs>(args?: Prisma.SelectSubset<T, DetallesCarritoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DetallesCarritos and returns the data saved in the database.
   * @param {DetallesCarritoCreateManyAndReturnArgs} args - Arguments to create many DetallesCarritos.
   * @example
   * // Create many DetallesCarritos
   * const detallesCarrito = await prisma.detallesCarrito.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DetallesCarritos and only return the `id`
   * const detallesCarritoWithIdOnly = await prisma.detallesCarrito.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DetallesCarritoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DetallesCarritoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DetallesCarrito.
   * @param {DetallesCarritoDeleteArgs} args - Arguments to delete one DetallesCarrito.
   * @example
   * // Delete one DetallesCarrito
   * const DetallesCarrito = await prisma.detallesCarrito.delete({
   *   where: {
   *     // ... filter to delete one DetallesCarrito
   *   }
   * })
   * 
   */
  delete<T extends DetallesCarritoDeleteArgs>(args: Prisma.SelectSubset<T, DetallesCarritoDeleteArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DetallesCarrito.
   * @param {DetallesCarritoUpdateArgs} args - Arguments to update one DetallesCarrito.
   * @example
   * // Update one DetallesCarrito
   * const detallesCarrito = await prisma.detallesCarrito.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DetallesCarritoUpdateArgs>(args: Prisma.SelectSubset<T, DetallesCarritoUpdateArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DetallesCarritos.
   * @param {DetallesCarritoDeleteManyArgs} args - Arguments to filter DetallesCarritos to delete.
   * @example
   * // Delete a few DetallesCarritos
   * const { count } = await prisma.detallesCarrito.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DetallesCarritoDeleteManyArgs>(args?: Prisma.SelectSubset<T, DetallesCarritoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DetallesCarritos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DetallesCarritos
   * const detallesCarrito = await prisma.detallesCarrito.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DetallesCarritoUpdateManyArgs>(args: Prisma.SelectSubset<T, DetallesCarritoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DetallesCarritos and returns the data updated in the database.
   * @param {DetallesCarritoUpdateManyAndReturnArgs} args - Arguments to update many DetallesCarritos.
   * @example
   * // Update many DetallesCarritos
   * const detallesCarrito = await prisma.detallesCarrito.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DetallesCarritos and only return the `id`
   * const detallesCarritoWithIdOnly = await prisma.detallesCarrito.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DetallesCarritoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DetallesCarritoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DetallesCarrito.
   * @param {DetallesCarritoUpsertArgs} args - Arguments to update or create a DetallesCarrito.
   * @example
   * // Update or create a DetallesCarrito
   * const detallesCarrito = await prisma.detallesCarrito.upsert({
   *   create: {
   *     // ... data to create a DetallesCarrito
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DetallesCarrito we want to update
   *   }
   * })
   */
  upsert<T extends DetallesCarritoUpsertArgs>(args: Prisma.SelectSubset<T, DetallesCarritoUpsertArgs<ExtArgs>>): Prisma.Prisma__DetallesCarritoClient<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DetallesCarritos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoCountArgs} args - Arguments to filter DetallesCarritos to count.
   * @example
   * // Count the number of DetallesCarritos
   * const count = await prisma.detallesCarrito.count({
   *   where: {
   *     // ... the filter for the DetallesCarritos we want to count
   *   }
   * })
  **/
  count<T extends DetallesCarritoCountArgs>(
    args?: Prisma.Subset<T, DetallesCarritoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DetallesCarritoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DetallesCarrito.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DetallesCarritoAggregateArgs>(args: Prisma.Subset<T, DetallesCarritoAggregateArgs>): Prisma.PrismaPromise<GetDetallesCarritoAggregateType<T>>

  /**
   * Group by DetallesCarrito.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DetallesCarritoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DetallesCarritoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DetallesCarritoGroupByArgs['orderBy'] }
      : { orderBy?: DetallesCarritoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DetallesCarritoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDetallesCarritoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DetallesCarrito model
 */
readonly fields: DetallesCarritoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DetallesCarrito.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DetallesCarritoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Carrito<T extends Prisma.CarritosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CarritosDefaultArgs<ExtArgs>>): Prisma.Prisma__CarritosClient<runtime.Types.Result.GetResult<Prisma.$CarritosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Libros<T extends Prisma.LibrosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LibrosDefaultArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DetallesCarrito model
 */
export interface DetallesCarritoFieldRefs {
  readonly id: Prisma.FieldRef<"DetallesCarrito", 'Int'>
  readonly carrito_id: Prisma.FieldRef<"DetallesCarrito", 'Int'>
  readonly libro_id: Prisma.FieldRef<"DetallesCarrito", 'Int'>
  readonly cantidad: Prisma.FieldRef<"DetallesCarrito", 'Int'>
  readonly precio: Prisma.FieldRef<"DetallesCarrito", 'Decimal'>
  readonly es_digital: Prisma.FieldRef<"DetallesCarrito", 'Boolean'>
}
    

// Custom InputTypes
/**
 * DetallesCarrito findUnique
 */
export type DetallesCarritoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * Filter, which DetallesCarrito to fetch.
   */
  where: Prisma.DetallesCarritoWhereUniqueInput
}

/**
 * DetallesCarrito findUniqueOrThrow
 */
export type DetallesCarritoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * Filter, which DetallesCarrito to fetch.
   */
  where: Prisma.DetallesCarritoWhereUniqueInput
}

/**
 * DetallesCarrito findFirst
 */
export type DetallesCarritoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * Filter, which DetallesCarrito to fetch.
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DetallesCarritos to fetch.
   */
  orderBy?: Prisma.DetallesCarritoOrderByWithRelationInput | Prisma.DetallesCarritoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DetallesCarritos.
   */
  cursor?: Prisma.DetallesCarritoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DetallesCarritos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DetallesCarritos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DetallesCarritos.
   */
  distinct?: Prisma.DetallesCarritoScalarFieldEnum | Prisma.DetallesCarritoScalarFieldEnum[]
}

/**
 * DetallesCarrito findFirstOrThrow
 */
export type DetallesCarritoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * Filter, which DetallesCarrito to fetch.
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DetallesCarritos to fetch.
   */
  orderBy?: Prisma.DetallesCarritoOrderByWithRelationInput | Prisma.DetallesCarritoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DetallesCarritos.
   */
  cursor?: Prisma.DetallesCarritoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DetallesCarritos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DetallesCarritos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DetallesCarritos.
   */
  distinct?: Prisma.DetallesCarritoScalarFieldEnum | Prisma.DetallesCarritoScalarFieldEnum[]
}

/**
 * DetallesCarrito findMany
 */
export type DetallesCarritoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * Filter, which DetallesCarritos to fetch.
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DetallesCarritos to fetch.
   */
  orderBy?: Prisma.DetallesCarritoOrderByWithRelationInput | Prisma.DetallesCarritoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DetallesCarritos.
   */
  cursor?: Prisma.DetallesCarritoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DetallesCarritos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DetallesCarritos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DetallesCarritos.
   */
  distinct?: Prisma.DetallesCarritoScalarFieldEnum | Prisma.DetallesCarritoScalarFieldEnum[]
}

/**
 * DetallesCarrito create
 */
export type DetallesCarritoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * The data needed to create a DetallesCarrito.
   */
  data: Prisma.XOR<Prisma.DetallesCarritoCreateInput, Prisma.DetallesCarritoUncheckedCreateInput>
}

/**
 * DetallesCarrito createMany
 */
export type DetallesCarritoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DetallesCarritos.
   */
  data: Prisma.DetallesCarritoCreateManyInput | Prisma.DetallesCarritoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DetallesCarrito createManyAndReturn
 */
export type DetallesCarritoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * The data used to create many DetallesCarritos.
   */
  data: Prisma.DetallesCarritoCreateManyInput | Prisma.DetallesCarritoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DetallesCarrito update
 */
export type DetallesCarritoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * The data needed to update a DetallesCarrito.
   */
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateInput, Prisma.DetallesCarritoUncheckedUpdateInput>
  /**
   * Choose, which DetallesCarrito to update.
   */
  where: Prisma.DetallesCarritoWhereUniqueInput
}

/**
 * DetallesCarrito updateMany
 */
export type DetallesCarritoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DetallesCarritos.
   */
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateManyMutationInput, Prisma.DetallesCarritoUncheckedUpdateManyInput>
  /**
   * Filter which DetallesCarritos to update
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * Limit how many DetallesCarritos to update.
   */
  limit?: number
}

/**
 * DetallesCarrito updateManyAndReturn
 */
export type DetallesCarritoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * The data used to update DetallesCarritos.
   */
  data: Prisma.XOR<Prisma.DetallesCarritoUpdateManyMutationInput, Prisma.DetallesCarritoUncheckedUpdateManyInput>
  /**
   * Filter which DetallesCarritos to update
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * Limit how many DetallesCarritos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DetallesCarrito upsert
 */
export type DetallesCarritoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * The filter to search for the DetallesCarrito to update in case it exists.
   */
  where: Prisma.DetallesCarritoWhereUniqueInput
  /**
   * In case the DetallesCarrito found by the `where` argument doesn't exist, create a new DetallesCarrito with this data.
   */
  create: Prisma.XOR<Prisma.DetallesCarritoCreateInput, Prisma.DetallesCarritoUncheckedCreateInput>
  /**
   * In case the DetallesCarrito was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DetallesCarritoUpdateInput, Prisma.DetallesCarritoUncheckedUpdateInput>
}

/**
 * DetallesCarrito delete
 */
export type DetallesCarritoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  /**
   * Filter which DetallesCarrito to delete.
   */
  where: Prisma.DetallesCarritoWhereUniqueInput
}

/**
 * DetallesCarrito deleteMany
 */
export type DetallesCarritoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DetallesCarritos to delete
   */
  where?: Prisma.DetallesCarritoWhereInput
  /**
   * Limit how many DetallesCarritos to delete.
   */
  limit?: number
}

/**
 * DetallesCarrito without action
 */
export type DetallesCarritoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
}
