
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListaProveedor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ListaProveedor
 * 
 */
export type ListaProveedorModel = runtime.Types.Result.DefaultSelection<Prisma.$ListaProveedorPayload>

export type AggregateListaProveedor = {
  _count: ListaProveedorCountAggregateOutputType | null
  _avg: ListaProveedorAvgAggregateOutputType | null
  _sum: ListaProveedorSumAggregateOutputType | null
  _min: ListaProveedorMinAggregateOutputType | null
  _max: ListaProveedorMaxAggregateOutputType | null
}

export type ListaProveedorAvgAggregateOutputType = {
  id: number | null
  usuario_id: number | null
}

export type ListaProveedorSumAggregateOutputType = {
  id: number | null
  usuario_id: number | null
}

export type ListaProveedorMinAggregateOutputType = {
  id: number | null
  usuario_id: number | null
  es_proveedor: boolean | null
  fecha_solicitud: Date | null
}

export type ListaProveedorMaxAggregateOutputType = {
  id: number | null
  usuario_id: number | null
  es_proveedor: boolean | null
  fecha_solicitud: Date | null
}

export type ListaProveedorCountAggregateOutputType = {
  id: number
  usuario_id: number
  es_proveedor: number
  fecha_solicitud: number
  _all: number
}


export type ListaProveedorAvgAggregateInputType = {
  id?: true
  usuario_id?: true
}

export type ListaProveedorSumAggregateInputType = {
  id?: true
  usuario_id?: true
}

export type ListaProveedorMinAggregateInputType = {
  id?: true
  usuario_id?: true
  es_proveedor?: true
  fecha_solicitud?: true
}

export type ListaProveedorMaxAggregateInputType = {
  id?: true
  usuario_id?: true
  es_proveedor?: true
  fecha_solicitud?: true
}

export type ListaProveedorCountAggregateInputType = {
  id?: true
  usuario_id?: true
  es_proveedor?: true
  fecha_solicitud?: true
  _all?: true
}

export type ListaProveedorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListaProveedor to aggregate.
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListaProveedors to fetch.
   */
  orderBy?: Prisma.ListaProveedorOrderByWithRelationInput | Prisma.ListaProveedorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListaProveedorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListaProveedors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListaProveedors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListaProveedors
  **/
  _count?: true | ListaProveedorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ListaProveedorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ListaProveedorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListaProveedorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListaProveedorMaxAggregateInputType
}

export type GetListaProveedorAggregateType<T extends ListaProveedorAggregateArgs> = {
      [P in keyof T & keyof AggregateListaProveedor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListaProveedor[P]>
    : Prisma.GetScalarType<T[P], AggregateListaProveedor[P]>
}




export type ListaProveedorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListaProveedorWhereInput
  orderBy?: Prisma.ListaProveedorOrderByWithAggregationInput | Prisma.ListaProveedorOrderByWithAggregationInput[]
  by: Prisma.ListaProveedorScalarFieldEnum[] | Prisma.ListaProveedorScalarFieldEnum
  having?: Prisma.ListaProveedorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListaProveedorCountAggregateInputType | true
  _avg?: ListaProveedorAvgAggregateInputType
  _sum?: ListaProveedorSumAggregateInputType
  _min?: ListaProveedorMinAggregateInputType
  _max?: ListaProveedorMaxAggregateInputType
}

export type ListaProveedorGroupByOutputType = {
  id: number
  usuario_id: number
  es_proveedor: boolean
  fecha_solicitud: Date
  _count: ListaProveedorCountAggregateOutputType | null
  _avg: ListaProveedorAvgAggregateOutputType | null
  _sum: ListaProveedorSumAggregateOutputType | null
  _min: ListaProveedorMinAggregateOutputType | null
  _max: ListaProveedorMaxAggregateOutputType | null
}

export type GetListaProveedorGroupByPayload<T extends ListaProveedorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListaProveedorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListaProveedorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListaProveedorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListaProveedorGroupByOutputType[P]>
      }
    >
  >



export type ListaProveedorWhereInput = {
  AND?: Prisma.ListaProveedorWhereInput | Prisma.ListaProveedorWhereInput[]
  OR?: Prisma.ListaProveedorWhereInput[]
  NOT?: Prisma.ListaProveedorWhereInput | Prisma.ListaProveedorWhereInput[]
  id?: Prisma.IntFilter<"ListaProveedor"> | number
  usuario_id?: Prisma.IntFilter<"ListaProveedor"> | number
  es_proveedor?: Prisma.BoolFilter<"ListaProveedor"> | boolean
  fecha_solicitud?: Prisma.DateTimeFilter<"ListaProveedor"> | Date | string
  Usuario?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
}

export type ListaProveedorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  es_proveedor?: Prisma.SortOrder
  fecha_solicitud?: Prisma.SortOrder
  Usuario?: Prisma.UsuariosOrderByWithRelationInput
}

export type ListaProveedorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  usuario_id?: number
  AND?: Prisma.ListaProveedorWhereInput | Prisma.ListaProveedorWhereInput[]
  OR?: Prisma.ListaProveedorWhereInput[]
  NOT?: Prisma.ListaProveedorWhereInput | Prisma.ListaProveedorWhereInput[]
  es_proveedor?: Prisma.BoolFilter<"ListaProveedor"> | boolean
  fecha_solicitud?: Prisma.DateTimeFilter<"ListaProveedor"> | Date | string
  Usuario?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
}, "id" | "usuario_id">

export type ListaProveedorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  es_proveedor?: Prisma.SortOrder
  fecha_solicitud?: Prisma.SortOrder
  _count?: Prisma.ListaProveedorCountOrderByAggregateInput
  _avg?: Prisma.ListaProveedorAvgOrderByAggregateInput
  _max?: Prisma.ListaProveedorMaxOrderByAggregateInput
  _min?: Prisma.ListaProveedorMinOrderByAggregateInput
  _sum?: Prisma.ListaProveedorSumOrderByAggregateInput
}

export type ListaProveedorScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListaProveedorScalarWhereWithAggregatesInput | Prisma.ListaProveedorScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListaProveedorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListaProveedorScalarWhereWithAggregatesInput | Prisma.ListaProveedorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ListaProveedor"> | number
  usuario_id?: Prisma.IntWithAggregatesFilter<"ListaProveedor"> | number
  es_proveedor?: Prisma.BoolWithAggregatesFilter<"ListaProveedor"> | boolean
  fecha_solicitud?: Prisma.DateTimeWithAggregatesFilter<"ListaProveedor"> | Date | string
}

export type ListaProveedorCreateInput = {
  es_proveedor?: boolean
  fecha_solicitud?: Date | string
  Usuario: Prisma.UsuariosCreateNestedOneWithoutListaProveedorInput
}

export type ListaProveedorUncheckedCreateInput = {
  id?: number
  usuario_id: number
  es_proveedor?: boolean
  fecha_solicitud?: Date | string
}

export type ListaProveedorUpdateInput = {
  es_proveedor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fecha_solicitud?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Usuario?: Prisma.UsuariosUpdateOneRequiredWithoutListaProveedorNestedInput
}

export type ListaProveedorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  es_proveedor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fecha_solicitud?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListaProveedorCreateManyInput = {
  id?: number
  usuario_id: number
  es_proveedor?: boolean
  fecha_solicitud?: Date | string
}

export type ListaProveedorUpdateManyMutationInput = {
  es_proveedor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fecha_solicitud?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListaProveedorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  es_proveedor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fecha_solicitud?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListaProveedorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  es_proveedor?: Prisma.SortOrder
  fecha_solicitud?: Prisma.SortOrder
}

export type ListaProveedorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
}

export type ListaProveedorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  es_proveedor?: Prisma.SortOrder
  fecha_solicitud?: Prisma.SortOrder
}

export type ListaProveedorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
  es_proveedor?: Prisma.SortOrder
  fecha_solicitud?: Prisma.SortOrder
}

export type ListaProveedorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuario_id?: Prisma.SortOrder
}

export type ListaProveedorNullableScalarRelationFilter = {
  is?: Prisma.ListaProveedorWhereInput | null
  isNot?: Prisma.ListaProveedorWhereInput | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ListaProveedorCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.ListaProveedorCreateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ListaProveedorCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.ListaProveedorWhereUniqueInput
}

export type ListaProveedorUncheckedCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.ListaProveedorCreateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ListaProveedorCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.ListaProveedorWhereUniqueInput
}

export type ListaProveedorUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.ListaProveedorCreateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ListaProveedorCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.ListaProveedorUpsertWithoutUsuarioInput
  disconnect?: Prisma.ListaProveedorWhereInput | boolean
  delete?: Prisma.ListaProveedorWhereInput | boolean
  connect?: Prisma.ListaProveedorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListaProveedorUpdateToOneWithWhereWithoutUsuarioInput, Prisma.ListaProveedorUpdateWithoutUsuarioInput>, Prisma.ListaProveedorUncheckedUpdateWithoutUsuarioInput>
}

export type ListaProveedorUncheckedUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.ListaProveedorCreateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ListaProveedorCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.ListaProveedorUpsertWithoutUsuarioInput
  disconnect?: Prisma.ListaProveedorWhereInput | boolean
  delete?: Prisma.ListaProveedorWhereInput | boolean
  connect?: Prisma.ListaProveedorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ListaProveedorUpdateToOneWithWhereWithoutUsuarioInput, Prisma.ListaProveedorUpdateWithoutUsuarioInput>, Prisma.ListaProveedorUncheckedUpdateWithoutUsuarioInput>
}

export type ListaProveedorCreateWithoutUsuarioInput = {
  es_proveedor?: boolean
  fecha_solicitud?: Date | string
}

export type ListaProveedorUncheckedCreateWithoutUsuarioInput = {
  id?: number
  es_proveedor?: boolean
  fecha_solicitud?: Date | string
}

export type ListaProveedorCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.ListaProveedorWhereUniqueInput
  create: Prisma.XOR<Prisma.ListaProveedorCreateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedCreateWithoutUsuarioInput>
}

export type ListaProveedorUpsertWithoutUsuarioInput = {
  update: Prisma.XOR<Prisma.ListaProveedorUpdateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.ListaProveedorCreateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedCreateWithoutUsuarioInput>
  where?: Prisma.ListaProveedorWhereInput
}

export type ListaProveedorUpdateToOneWithWhereWithoutUsuarioInput = {
  where?: Prisma.ListaProveedorWhereInput
  data: Prisma.XOR<Prisma.ListaProveedorUpdateWithoutUsuarioInput, Prisma.ListaProveedorUncheckedUpdateWithoutUsuarioInput>
}

export type ListaProveedorUpdateWithoutUsuarioInput = {
  es_proveedor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fecha_solicitud?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListaProveedorUncheckedUpdateWithoutUsuarioInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  es_proveedor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fecha_solicitud?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ListaProveedorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  es_proveedor?: boolean
  fecha_solicitud?: boolean
  Usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listaProveedor"]>

export type ListaProveedorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  es_proveedor?: boolean
  fecha_solicitud?: boolean
  Usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listaProveedor"]>

export type ListaProveedorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuario_id?: boolean
  es_proveedor?: boolean
  fecha_solicitud?: boolean
  Usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listaProveedor"]>

export type ListaProveedorSelectScalar = {
  id?: boolean
  usuario_id?: boolean
  es_proveedor?: boolean
  fecha_solicitud?: boolean
}

export type ListaProveedorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "usuario_id" | "es_proveedor" | "fecha_solicitud", ExtArgs["result"]["listaProveedor"]>
export type ListaProveedorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type ListaProveedorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type ListaProveedorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}

export type $ListaProveedorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListaProveedor"
  objects: {
    Usuario: Prisma.$UsuariosPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    usuario_id: number
    es_proveedor: boolean
    fecha_solicitud: Date
  }, ExtArgs["result"]["listaProveedor"]>
  composites: {}
}

export type ListaProveedorGetPayload<S extends boolean | null | undefined | ListaProveedorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload, S>

export type ListaProveedorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListaProveedorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListaProveedorCountAggregateInputType | true
  }

export interface ListaProveedorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListaProveedor'], meta: { name: 'ListaProveedor' } }
  /**
   * Find zero or one ListaProveedor that matches the filter.
   * @param {ListaProveedorFindUniqueArgs} args - Arguments to find a ListaProveedor
   * @example
   * // Get one ListaProveedor
   * const listaProveedor = await prisma.listaProveedor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListaProveedorFindUniqueArgs>(args: Prisma.SelectSubset<T, ListaProveedorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListaProveedor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListaProveedorFindUniqueOrThrowArgs} args - Arguments to find a ListaProveedor
   * @example
   * // Get one ListaProveedor
   * const listaProveedor = await prisma.listaProveedor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListaProveedorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListaProveedorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListaProveedor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorFindFirstArgs} args - Arguments to find a ListaProveedor
   * @example
   * // Get one ListaProveedor
   * const listaProveedor = await prisma.listaProveedor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListaProveedorFindFirstArgs>(args?: Prisma.SelectSubset<T, ListaProveedorFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListaProveedor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorFindFirstOrThrowArgs} args - Arguments to find a ListaProveedor
   * @example
   * // Get one ListaProveedor
   * const listaProveedor = await prisma.listaProveedor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListaProveedorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListaProveedorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListaProveedors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListaProveedors
   * const listaProveedors = await prisma.listaProveedor.findMany()
   * 
   * // Get first 10 ListaProveedors
   * const listaProveedors = await prisma.listaProveedor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const listaProveedorWithIdOnly = await prisma.listaProveedor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ListaProveedorFindManyArgs>(args?: Prisma.SelectSubset<T, ListaProveedorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListaProveedor.
   * @param {ListaProveedorCreateArgs} args - Arguments to create a ListaProveedor.
   * @example
   * // Create one ListaProveedor
   * const ListaProveedor = await prisma.listaProveedor.create({
   *   data: {
   *     // ... data to create a ListaProveedor
   *   }
   * })
   * 
   */
  create<T extends ListaProveedorCreateArgs>(args: Prisma.SelectSubset<T, ListaProveedorCreateArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListaProveedors.
   * @param {ListaProveedorCreateManyArgs} args - Arguments to create many ListaProveedors.
   * @example
   * // Create many ListaProveedors
   * const listaProveedor = await prisma.listaProveedor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListaProveedorCreateManyArgs>(args?: Prisma.SelectSubset<T, ListaProveedorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListaProveedors and returns the data saved in the database.
   * @param {ListaProveedorCreateManyAndReturnArgs} args - Arguments to create many ListaProveedors.
   * @example
   * // Create many ListaProveedors
   * const listaProveedor = await prisma.listaProveedor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListaProveedors and only return the `id`
   * const listaProveedorWithIdOnly = await prisma.listaProveedor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListaProveedorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListaProveedorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListaProveedor.
   * @param {ListaProveedorDeleteArgs} args - Arguments to delete one ListaProveedor.
   * @example
   * // Delete one ListaProveedor
   * const ListaProveedor = await prisma.listaProveedor.delete({
   *   where: {
   *     // ... filter to delete one ListaProveedor
   *   }
   * })
   * 
   */
  delete<T extends ListaProveedorDeleteArgs>(args: Prisma.SelectSubset<T, ListaProveedorDeleteArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListaProveedor.
   * @param {ListaProveedorUpdateArgs} args - Arguments to update one ListaProveedor.
   * @example
   * // Update one ListaProveedor
   * const listaProveedor = await prisma.listaProveedor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListaProveedorUpdateArgs>(args: Prisma.SelectSubset<T, ListaProveedorUpdateArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListaProveedors.
   * @param {ListaProveedorDeleteManyArgs} args - Arguments to filter ListaProveedors to delete.
   * @example
   * // Delete a few ListaProveedors
   * const { count } = await prisma.listaProveedor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListaProveedorDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListaProveedorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListaProveedors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListaProveedors
   * const listaProveedor = await prisma.listaProveedor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListaProveedorUpdateManyArgs>(args: Prisma.SelectSubset<T, ListaProveedorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListaProveedors and returns the data updated in the database.
   * @param {ListaProveedorUpdateManyAndReturnArgs} args - Arguments to update many ListaProveedors.
   * @example
   * // Update many ListaProveedors
   * const listaProveedor = await prisma.listaProveedor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListaProveedors and only return the `id`
   * const listaProveedorWithIdOnly = await prisma.listaProveedor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListaProveedorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListaProveedorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListaProveedor.
   * @param {ListaProveedorUpsertArgs} args - Arguments to update or create a ListaProveedor.
   * @example
   * // Update or create a ListaProveedor
   * const listaProveedor = await prisma.listaProveedor.upsert({
   *   create: {
   *     // ... data to create a ListaProveedor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListaProveedor we want to update
   *   }
   * })
   */
  upsert<T extends ListaProveedorUpsertArgs>(args: Prisma.SelectSubset<T, ListaProveedorUpsertArgs<ExtArgs>>): Prisma.Prisma__ListaProveedorClient<runtime.Types.Result.GetResult<Prisma.$ListaProveedorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListaProveedors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorCountArgs} args - Arguments to filter ListaProveedors to count.
   * @example
   * // Count the number of ListaProveedors
   * const count = await prisma.listaProveedor.count({
   *   where: {
   *     // ... the filter for the ListaProveedors we want to count
   *   }
   * })
  **/
  count<T extends ListaProveedorCountArgs>(
    args?: Prisma.Subset<T, ListaProveedorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListaProveedorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListaProveedor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListaProveedorAggregateArgs>(args: Prisma.Subset<T, ListaProveedorAggregateArgs>): Prisma.PrismaPromise<GetListaProveedorAggregateType<T>>

  /**
   * Group by ListaProveedor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListaProveedorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListaProveedorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListaProveedorGroupByArgs['orderBy'] }
      : { orderBy?: ListaProveedorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListaProveedorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListaProveedorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListaProveedor model
 */
readonly fields: ListaProveedorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListaProveedor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListaProveedorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Usuario<T extends Prisma.UsuariosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuariosDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListaProveedor model
 */
export interface ListaProveedorFieldRefs {
  readonly id: Prisma.FieldRef<"ListaProveedor", 'Int'>
  readonly usuario_id: Prisma.FieldRef<"ListaProveedor", 'Int'>
  readonly es_proveedor: Prisma.FieldRef<"ListaProveedor", 'Boolean'>
  readonly fecha_solicitud: Prisma.FieldRef<"ListaProveedor", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ListaProveedor findUnique
 */
export type ListaProveedorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * Filter, which ListaProveedor to fetch.
   */
  where: Prisma.ListaProveedorWhereUniqueInput
}

/**
 * ListaProveedor findUniqueOrThrow
 */
export type ListaProveedorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * Filter, which ListaProveedor to fetch.
   */
  where: Prisma.ListaProveedorWhereUniqueInput
}

/**
 * ListaProveedor findFirst
 */
export type ListaProveedorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * Filter, which ListaProveedor to fetch.
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListaProveedors to fetch.
   */
  orderBy?: Prisma.ListaProveedorOrderByWithRelationInput | Prisma.ListaProveedorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListaProveedors.
   */
  cursor?: Prisma.ListaProveedorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListaProveedors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListaProveedors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListaProveedors.
   */
  distinct?: Prisma.ListaProveedorScalarFieldEnum | Prisma.ListaProveedorScalarFieldEnum[]
}

/**
 * ListaProveedor findFirstOrThrow
 */
export type ListaProveedorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * Filter, which ListaProveedor to fetch.
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListaProveedors to fetch.
   */
  orderBy?: Prisma.ListaProveedorOrderByWithRelationInput | Prisma.ListaProveedorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListaProveedors.
   */
  cursor?: Prisma.ListaProveedorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListaProveedors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListaProveedors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListaProveedors.
   */
  distinct?: Prisma.ListaProveedorScalarFieldEnum | Prisma.ListaProveedorScalarFieldEnum[]
}

/**
 * ListaProveedor findMany
 */
export type ListaProveedorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * Filter, which ListaProveedors to fetch.
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListaProveedors to fetch.
   */
  orderBy?: Prisma.ListaProveedorOrderByWithRelationInput | Prisma.ListaProveedorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListaProveedors.
   */
  cursor?: Prisma.ListaProveedorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListaProveedors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListaProveedors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListaProveedors.
   */
  distinct?: Prisma.ListaProveedorScalarFieldEnum | Prisma.ListaProveedorScalarFieldEnum[]
}

/**
 * ListaProveedor create
 */
export type ListaProveedorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * The data needed to create a ListaProveedor.
   */
  data: Prisma.XOR<Prisma.ListaProveedorCreateInput, Prisma.ListaProveedorUncheckedCreateInput>
}

/**
 * ListaProveedor createMany
 */
export type ListaProveedorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListaProveedors.
   */
  data: Prisma.ListaProveedorCreateManyInput | Prisma.ListaProveedorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListaProveedor createManyAndReturn
 */
export type ListaProveedorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * The data used to create many ListaProveedors.
   */
  data: Prisma.ListaProveedorCreateManyInput | Prisma.ListaProveedorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ListaProveedor update
 */
export type ListaProveedorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * The data needed to update a ListaProveedor.
   */
  data: Prisma.XOR<Prisma.ListaProveedorUpdateInput, Prisma.ListaProveedorUncheckedUpdateInput>
  /**
   * Choose, which ListaProveedor to update.
   */
  where: Prisma.ListaProveedorWhereUniqueInput
}

/**
 * ListaProveedor updateMany
 */
export type ListaProveedorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListaProveedors.
   */
  data: Prisma.XOR<Prisma.ListaProveedorUpdateManyMutationInput, Prisma.ListaProveedorUncheckedUpdateManyInput>
  /**
   * Filter which ListaProveedors to update
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * Limit how many ListaProveedors to update.
   */
  limit?: number
}

/**
 * ListaProveedor updateManyAndReturn
 */
export type ListaProveedorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * The data used to update ListaProveedors.
   */
  data: Prisma.XOR<Prisma.ListaProveedorUpdateManyMutationInput, Prisma.ListaProveedorUncheckedUpdateManyInput>
  /**
   * Filter which ListaProveedors to update
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * Limit how many ListaProveedors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ListaProveedor upsert
 */
export type ListaProveedorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * The filter to search for the ListaProveedor to update in case it exists.
   */
  where: Prisma.ListaProveedorWhereUniqueInput
  /**
   * In case the ListaProveedor found by the `where` argument doesn't exist, create a new ListaProveedor with this data.
   */
  create: Prisma.XOR<Prisma.ListaProveedorCreateInput, Prisma.ListaProveedorUncheckedCreateInput>
  /**
   * In case the ListaProveedor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListaProveedorUpdateInput, Prisma.ListaProveedorUncheckedUpdateInput>
}

/**
 * ListaProveedor delete
 */
export type ListaProveedorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
  /**
   * Filter which ListaProveedor to delete.
   */
  where: Prisma.ListaProveedorWhereUniqueInput
}

/**
 * ListaProveedor deleteMany
 */
export type ListaProveedorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListaProveedors to delete
   */
  where?: Prisma.ListaProveedorWhereInput
  /**
   * Limit how many ListaProveedors to delete.
   */
  limit?: number
}

/**
 * ListaProveedor without action
 */
export type ListaProveedorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListaProveedor
   */
  select?: Prisma.ListaProveedorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListaProveedor
   */
  omit?: Prisma.ListaProveedorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ListaProveedorInclude<ExtArgs> | null
}
