
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Proveedores` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Proveedores
 * 
 */
export type ProveedoresModel = runtime.Types.Result.DefaultSelection<Prisma.$ProveedoresPayload>

export type AggregateProveedores = {
  _count: ProveedoresCountAggregateOutputType | null
  _avg: ProveedoresAvgAggregateOutputType | null
  _sum: ProveedoresSumAggregateOutputType | null
  _min: ProveedoresMinAggregateOutputType | null
  _max: ProveedoresMaxAggregateOutputType | null
}

export type ProveedoresAvgAggregateOutputType = {
  usuario_id: number | null
}

export type ProveedoresSumAggregateOutputType = {
  usuario_id: number | null
}

export type ProveedoresMinAggregateOutputType = {
  usuario_id: number | null
}

export type ProveedoresMaxAggregateOutputType = {
  usuario_id: number | null
}

export type ProveedoresCountAggregateOutputType = {
  usuario_id: number
  _all: number
}


export type ProveedoresAvgAggregateInputType = {
  usuario_id?: true
}

export type ProveedoresSumAggregateInputType = {
  usuario_id?: true
}

export type ProveedoresMinAggregateInputType = {
  usuario_id?: true
}

export type ProveedoresMaxAggregateInputType = {
  usuario_id?: true
}

export type ProveedoresCountAggregateInputType = {
  usuario_id?: true
  _all?: true
}

export type ProveedoresAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proveedores to aggregate.
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proveedores to fetch.
   */
  orderBy?: Prisma.ProveedoresOrderByWithRelationInput | Prisma.ProveedoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProveedoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proveedores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proveedores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Proveedores
  **/
  _count?: true | ProveedoresCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProveedoresAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProveedoresSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProveedoresMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProveedoresMaxAggregateInputType
}

export type GetProveedoresAggregateType<T extends ProveedoresAggregateArgs> = {
      [P in keyof T & keyof AggregateProveedores]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProveedores[P]>
    : Prisma.GetScalarType<T[P], AggregateProveedores[P]>
}




export type ProveedoresGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProveedoresWhereInput
  orderBy?: Prisma.ProveedoresOrderByWithAggregationInput | Prisma.ProveedoresOrderByWithAggregationInput[]
  by: Prisma.ProveedoresScalarFieldEnum[] | Prisma.ProveedoresScalarFieldEnum
  having?: Prisma.ProveedoresScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProveedoresCountAggregateInputType | true
  _avg?: ProveedoresAvgAggregateInputType
  _sum?: ProveedoresSumAggregateInputType
  _min?: ProveedoresMinAggregateInputType
  _max?: ProveedoresMaxAggregateInputType
}

export type ProveedoresGroupByOutputType = {
  usuario_id: number
  _count: ProveedoresCountAggregateOutputType | null
  _avg: ProveedoresAvgAggregateOutputType | null
  _sum: ProveedoresSumAggregateOutputType | null
  _min: ProveedoresMinAggregateOutputType | null
  _max: ProveedoresMaxAggregateOutputType | null
}

export type GetProveedoresGroupByPayload<T extends ProveedoresGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProveedoresGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProveedoresGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProveedoresGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProveedoresGroupByOutputType[P]>
      }
    >
  >



export type ProveedoresWhereInput = {
  AND?: Prisma.ProveedoresWhereInput | Prisma.ProveedoresWhereInput[]
  OR?: Prisma.ProveedoresWhereInput[]
  NOT?: Prisma.ProveedoresWhereInput | Prisma.ProveedoresWhereInput[]
  usuario_id?: Prisma.IntFilter<"Proveedores"> | number
  ofertas?: Prisma.OfertaLibroListRelationFilter
  Usuarios?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
}

export type ProveedoresOrderByWithRelationInput = {
  usuario_id?: Prisma.SortOrder
  ofertas?: Prisma.OfertaLibroOrderByRelationAggregateInput
  Usuarios?: Prisma.UsuariosOrderByWithRelationInput
}

export type ProveedoresWhereUniqueInput = Prisma.AtLeast<{
  usuario_id?: number
  AND?: Prisma.ProveedoresWhereInput | Prisma.ProveedoresWhereInput[]
  OR?: Prisma.ProveedoresWhereInput[]
  NOT?: Prisma.ProveedoresWhereInput | Prisma.ProveedoresWhereInput[]
  ofertas?: Prisma.OfertaLibroListRelationFilter
  Usuarios?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
}, "usuario_id">

export type ProveedoresOrderByWithAggregationInput = {
  usuario_id?: Prisma.SortOrder
  _count?: Prisma.ProveedoresCountOrderByAggregateInput
  _avg?: Prisma.ProveedoresAvgOrderByAggregateInput
  _max?: Prisma.ProveedoresMaxOrderByAggregateInput
  _min?: Prisma.ProveedoresMinOrderByAggregateInput
  _sum?: Prisma.ProveedoresSumOrderByAggregateInput
}

export type ProveedoresScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProveedoresScalarWhereWithAggregatesInput | Prisma.ProveedoresScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProveedoresScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProveedoresScalarWhereWithAggregatesInput | Prisma.ProveedoresScalarWhereWithAggregatesInput[]
  usuario_id?: Prisma.IntWithAggregatesFilter<"Proveedores"> | number
}

export type ProveedoresCreateInput = {
  ofertas?: Prisma.OfertaLibroCreateNestedManyWithoutProveedorInput
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutProveedoresInput
}

export type ProveedoresUncheckedCreateInput = {
  usuario_id: number
  ofertas?: Prisma.OfertaLibroUncheckedCreateNestedManyWithoutProveedorInput
}

export type ProveedoresUpdateInput = {
  ofertas?: Prisma.OfertaLibroUpdateManyWithoutProveedorNestedInput
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutProveedoresNestedInput
}

export type ProveedoresUncheckedUpdateInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
  ofertas?: Prisma.OfertaLibroUncheckedUpdateManyWithoutProveedorNestedInput
}

export type ProveedoresCreateManyInput = {
  usuario_id: number
}

export type ProveedoresUpdateManyMutationInput = {

}

export type ProveedoresUncheckedUpdateManyInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ProveedoresCountOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type ProveedoresAvgOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type ProveedoresMaxOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type ProveedoresMinOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type ProveedoresSumOrderByAggregateInput = {
  usuario_id?: Prisma.SortOrder
}

export type ProveedoresNullableScalarRelationFilter = {
  is?: Prisma.ProveedoresWhereInput | null
  isNot?: Prisma.ProveedoresWhereInput | null
}

export type ProveedoresScalarRelationFilter = {
  is?: Prisma.ProveedoresWhereInput
  isNot?: Prisma.ProveedoresWhereInput
}

export type ProveedoresCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.ProveedoresCreateWithoutUsuariosInput, Prisma.ProveedoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.ProveedoresCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.ProveedoresWhereUniqueInput
}

export type ProveedoresUncheckedCreateNestedOneWithoutUsuariosInput = {
  create?: Prisma.XOR<Prisma.ProveedoresCreateWithoutUsuariosInput, Prisma.ProveedoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.ProveedoresCreateOrConnectWithoutUsuariosInput
  connect?: Prisma.ProveedoresWhereUniqueInput
}

export type ProveedoresUpdateOneWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.ProveedoresCreateWithoutUsuariosInput, Prisma.ProveedoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.ProveedoresCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.ProveedoresUpsertWithoutUsuariosInput
  disconnect?: Prisma.ProveedoresWhereInput | boolean
  delete?: Prisma.ProveedoresWhereInput | boolean
  connect?: Prisma.ProveedoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProveedoresUpdateToOneWithWhereWithoutUsuariosInput, Prisma.ProveedoresUpdateWithoutUsuariosInput>, Prisma.ProveedoresUncheckedUpdateWithoutUsuariosInput>
}

export type ProveedoresUncheckedUpdateOneWithoutUsuariosNestedInput = {
  create?: Prisma.XOR<Prisma.ProveedoresCreateWithoutUsuariosInput, Prisma.ProveedoresUncheckedCreateWithoutUsuariosInput>
  connectOrCreate?: Prisma.ProveedoresCreateOrConnectWithoutUsuariosInput
  upsert?: Prisma.ProveedoresUpsertWithoutUsuariosInput
  disconnect?: Prisma.ProveedoresWhereInput | boolean
  delete?: Prisma.ProveedoresWhereInput | boolean
  connect?: Prisma.ProveedoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProveedoresUpdateToOneWithWhereWithoutUsuariosInput, Prisma.ProveedoresUpdateWithoutUsuariosInput>, Prisma.ProveedoresUncheckedUpdateWithoutUsuariosInput>
}

export type ProveedoresCreateNestedOneWithoutOfertasInput = {
  create?: Prisma.XOR<Prisma.ProveedoresCreateWithoutOfertasInput, Prisma.ProveedoresUncheckedCreateWithoutOfertasInput>
  connectOrCreate?: Prisma.ProveedoresCreateOrConnectWithoutOfertasInput
  connect?: Prisma.ProveedoresWhereUniqueInput
}

export type ProveedoresUpdateOneRequiredWithoutOfertasNestedInput = {
  create?: Prisma.XOR<Prisma.ProveedoresCreateWithoutOfertasInput, Prisma.ProveedoresUncheckedCreateWithoutOfertasInput>
  connectOrCreate?: Prisma.ProveedoresCreateOrConnectWithoutOfertasInput
  upsert?: Prisma.ProveedoresUpsertWithoutOfertasInput
  connect?: Prisma.ProveedoresWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProveedoresUpdateToOneWithWhereWithoutOfertasInput, Prisma.ProveedoresUpdateWithoutOfertasInput>, Prisma.ProveedoresUncheckedUpdateWithoutOfertasInput>
}

export type ProveedoresCreateWithoutUsuariosInput = {
  ofertas?: Prisma.OfertaLibroCreateNestedManyWithoutProveedorInput
}

export type ProveedoresUncheckedCreateWithoutUsuariosInput = {
  ofertas?: Prisma.OfertaLibroUncheckedCreateNestedManyWithoutProveedorInput
}

export type ProveedoresCreateOrConnectWithoutUsuariosInput = {
  where: Prisma.ProveedoresWhereUniqueInput
  create: Prisma.XOR<Prisma.ProveedoresCreateWithoutUsuariosInput, Prisma.ProveedoresUncheckedCreateWithoutUsuariosInput>
}

export type ProveedoresUpsertWithoutUsuariosInput = {
  update: Prisma.XOR<Prisma.ProveedoresUpdateWithoutUsuariosInput, Prisma.ProveedoresUncheckedUpdateWithoutUsuariosInput>
  create: Prisma.XOR<Prisma.ProveedoresCreateWithoutUsuariosInput, Prisma.ProveedoresUncheckedCreateWithoutUsuariosInput>
  where?: Prisma.ProveedoresWhereInput
}

export type ProveedoresUpdateToOneWithWhereWithoutUsuariosInput = {
  where?: Prisma.ProveedoresWhereInput
  data: Prisma.XOR<Prisma.ProveedoresUpdateWithoutUsuariosInput, Prisma.ProveedoresUncheckedUpdateWithoutUsuariosInput>
}

export type ProveedoresUpdateWithoutUsuariosInput = {
  ofertas?: Prisma.OfertaLibroUpdateManyWithoutProveedorNestedInput
}

export type ProveedoresUncheckedUpdateWithoutUsuariosInput = {
  ofertas?: Prisma.OfertaLibroUncheckedUpdateManyWithoutProveedorNestedInput
}

export type ProveedoresCreateWithoutOfertasInput = {
  Usuarios: Prisma.UsuariosCreateNestedOneWithoutProveedoresInput
}

export type ProveedoresUncheckedCreateWithoutOfertasInput = {
  usuario_id: number
}

export type ProveedoresCreateOrConnectWithoutOfertasInput = {
  where: Prisma.ProveedoresWhereUniqueInput
  create: Prisma.XOR<Prisma.ProveedoresCreateWithoutOfertasInput, Prisma.ProveedoresUncheckedCreateWithoutOfertasInput>
}

export type ProveedoresUpsertWithoutOfertasInput = {
  update: Prisma.XOR<Prisma.ProveedoresUpdateWithoutOfertasInput, Prisma.ProveedoresUncheckedUpdateWithoutOfertasInput>
  create: Prisma.XOR<Prisma.ProveedoresCreateWithoutOfertasInput, Prisma.ProveedoresUncheckedCreateWithoutOfertasInput>
  where?: Prisma.ProveedoresWhereInput
}

export type ProveedoresUpdateToOneWithWhereWithoutOfertasInput = {
  where?: Prisma.ProveedoresWhereInput
  data: Prisma.XOR<Prisma.ProveedoresUpdateWithoutOfertasInput, Prisma.ProveedoresUncheckedUpdateWithoutOfertasInput>
}

export type ProveedoresUpdateWithoutOfertasInput = {
  Usuarios?: Prisma.UsuariosUpdateOneRequiredWithoutProveedoresNestedInput
}

export type ProveedoresUncheckedUpdateWithoutOfertasInput = {
  usuario_id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ProveedoresCountOutputType
 */

export type ProveedoresCountOutputType = {
  ofertas: number
}

export type ProveedoresCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ofertas?: boolean | ProveedoresCountOutputTypeCountOfertasArgs
}

/**
 * ProveedoresCountOutputType without action
 */
export type ProveedoresCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProveedoresCountOutputType
   */
  select?: Prisma.ProveedoresCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProveedoresCountOutputType without action
 */
export type ProveedoresCountOutputTypeCountOfertasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfertaLibroWhereInput
}


export type ProveedoresSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  ofertas?: boolean | Prisma.Proveedores$ofertasArgs<ExtArgs>
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ProveedoresCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proveedores"]>

export type ProveedoresSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proveedores"]>

export type ProveedoresSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usuario_id?: boolean
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proveedores"]>

export type ProveedoresSelectScalar = {
  usuario_id?: boolean
}

export type ProveedoresOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"usuario_id", ExtArgs["result"]["proveedores"]>
export type ProveedoresInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ofertas?: boolean | Prisma.Proveedores$ofertasArgs<ExtArgs>
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ProveedoresCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProveedoresIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type ProveedoresIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Usuarios?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}

export type $ProveedoresPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Proveedores"
  objects: {
    ofertas: Prisma.$OfertaLibroPayload<ExtArgs>[]
    Usuarios: Prisma.$UsuariosPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    usuario_id: number
  }, ExtArgs["result"]["proveedores"]>
  composites: {}
}

export type ProveedoresGetPayload<S extends boolean | null | undefined | ProveedoresDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload, S>

export type ProveedoresCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProveedoresFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProveedoresCountAggregateInputType | true
  }

export interface ProveedoresDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Proveedores'], meta: { name: 'Proveedores' } }
  /**
   * Find zero or one Proveedores that matches the filter.
   * @param {ProveedoresFindUniqueArgs} args - Arguments to find a Proveedores
   * @example
   * // Get one Proveedores
   * const proveedores = await prisma.proveedores.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProveedoresFindUniqueArgs>(args: Prisma.SelectSubset<T, ProveedoresFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Proveedores that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProveedoresFindUniqueOrThrowArgs} args - Arguments to find a Proveedores
   * @example
   * // Get one Proveedores
   * const proveedores = await prisma.proveedores.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProveedoresFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProveedoresFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proveedores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresFindFirstArgs} args - Arguments to find a Proveedores
   * @example
   * // Get one Proveedores
   * const proveedores = await prisma.proveedores.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProveedoresFindFirstArgs>(args?: Prisma.SelectSubset<T, ProveedoresFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proveedores that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresFindFirstOrThrowArgs} args - Arguments to find a Proveedores
   * @example
   * // Get one Proveedores
   * const proveedores = await prisma.proveedores.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProveedoresFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProveedoresFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Proveedores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Proveedores
   * const proveedores = await prisma.proveedores.findMany()
   * 
   * // Get first 10 Proveedores
   * const proveedores = await prisma.proveedores.findMany({ take: 10 })
   * 
   * // Only select the `usuario_id`
   * const proveedoresWithUsuario_idOnly = await prisma.proveedores.findMany({ select: { usuario_id: true } })
   * 
   */
  findMany<T extends ProveedoresFindManyArgs>(args?: Prisma.SelectSubset<T, ProveedoresFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Proveedores.
   * @param {ProveedoresCreateArgs} args - Arguments to create a Proveedores.
   * @example
   * // Create one Proveedores
   * const Proveedores = await prisma.proveedores.create({
   *   data: {
   *     // ... data to create a Proveedores
   *   }
   * })
   * 
   */
  create<T extends ProveedoresCreateArgs>(args: Prisma.SelectSubset<T, ProveedoresCreateArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Proveedores.
   * @param {ProveedoresCreateManyArgs} args - Arguments to create many Proveedores.
   * @example
   * // Create many Proveedores
   * const proveedores = await prisma.proveedores.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProveedoresCreateManyArgs>(args?: Prisma.SelectSubset<T, ProveedoresCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Proveedores and returns the data saved in the database.
   * @param {ProveedoresCreateManyAndReturnArgs} args - Arguments to create many Proveedores.
   * @example
   * // Create many Proveedores
   * const proveedores = await prisma.proveedores.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Proveedores and only return the `usuario_id`
   * const proveedoresWithUsuario_idOnly = await prisma.proveedores.createManyAndReturn({
   *   select: { usuario_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProveedoresCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProveedoresCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Proveedores.
   * @param {ProveedoresDeleteArgs} args - Arguments to delete one Proveedores.
   * @example
   * // Delete one Proveedores
   * const Proveedores = await prisma.proveedores.delete({
   *   where: {
   *     // ... filter to delete one Proveedores
   *   }
   * })
   * 
   */
  delete<T extends ProveedoresDeleteArgs>(args: Prisma.SelectSubset<T, ProveedoresDeleteArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Proveedores.
   * @param {ProveedoresUpdateArgs} args - Arguments to update one Proveedores.
   * @example
   * // Update one Proveedores
   * const proveedores = await prisma.proveedores.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProveedoresUpdateArgs>(args: Prisma.SelectSubset<T, ProveedoresUpdateArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Proveedores.
   * @param {ProveedoresDeleteManyArgs} args - Arguments to filter Proveedores to delete.
   * @example
   * // Delete a few Proveedores
   * const { count } = await prisma.proveedores.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProveedoresDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProveedoresDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proveedores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Proveedores
   * const proveedores = await prisma.proveedores.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProveedoresUpdateManyArgs>(args: Prisma.SelectSubset<T, ProveedoresUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proveedores and returns the data updated in the database.
   * @param {ProveedoresUpdateManyAndReturnArgs} args - Arguments to update many Proveedores.
   * @example
   * // Update many Proveedores
   * const proveedores = await prisma.proveedores.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Proveedores and only return the `usuario_id`
   * const proveedoresWithUsuario_idOnly = await prisma.proveedores.updateManyAndReturn({
   *   select: { usuario_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProveedoresUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProveedoresUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Proveedores.
   * @param {ProveedoresUpsertArgs} args - Arguments to update or create a Proveedores.
   * @example
   * // Update or create a Proveedores
   * const proveedores = await prisma.proveedores.upsert({
   *   create: {
   *     // ... data to create a Proveedores
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Proveedores we want to update
   *   }
   * })
   */
  upsert<T extends ProveedoresUpsertArgs>(args: Prisma.SelectSubset<T, ProveedoresUpsertArgs<ExtArgs>>): Prisma.Prisma__ProveedoresClient<runtime.Types.Result.GetResult<Prisma.$ProveedoresPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Proveedores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresCountArgs} args - Arguments to filter Proveedores to count.
   * @example
   * // Count the number of Proveedores
   * const count = await prisma.proveedores.count({
   *   where: {
   *     // ... the filter for the Proveedores we want to count
   *   }
   * })
  **/
  count<T extends ProveedoresCountArgs>(
    args?: Prisma.Subset<T, ProveedoresCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProveedoresCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Proveedores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProveedoresAggregateArgs>(args: Prisma.Subset<T, ProveedoresAggregateArgs>): Prisma.PrismaPromise<GetProveedoresAggregateType<T>>

  /**
   * Group by Proveedores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProveedoresGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProveedoresGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProveedoresGroupByArgs['orderBy'] }
      : { orderBy?: ProveedoresGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProveedoresGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProveedoresGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Proveedores model
 */
readonly fields: ProveedoresFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Proveedores.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProveedoresClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ofertas<T extends Prisma.Proveedores$ofertasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proveedores$ofertasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfertaLibroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Usuarios<T extends Prisma.UsuariosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuariosDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Proveedores model
 */
export interface ProveedoresFieldRefs {
  readonly usuario_id: Prisma.FieldRef<"Proveedores", 'Int'>
}
    

// Custom InputTypes
/**
 * Proveedores findUnique
 */
export type ProveedoresFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * Filter, which Proveedores to fetch.
   */
  where: Prisma.ProveedoresWhereUniqueInput
}

/**
 * Proveedores findUniqueOrThrow
 */
export type ProveedoresFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * Filter, which Proveedores to fetch.
   */
  where: Prisma.ProveedoresWhereUniqueInput
}

/**
 * Proveedores findFirst
 */
export type ProveedoresFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * Filter, which Proveedores to fetch.
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proveedores to fetch.
   */
  orderBy?: Prisma.ProveedoresOrderByWithRelationInput | Prisma.ProveedoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proveedores.
   */
  cursor?: Prisma.ProveedoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proveedores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proveedores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proveedores.
   */
  distinct?: Prisma.ProveedoresScalarFieldEnum | Prisma.ProveedoresScalarFieldEnum[]
}

/**
 * Proveedores findFirstOrThrow
 */
export type ProveedoresFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * Filter, which Proveedores to fetch.
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proveedores to fetch.
   */
  orderBy?: Prisma.ProveedoresOrderByWithRelationInput | Prisma.ProveedoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proveedores.
   */
  cursor?: Prisma.ProveedoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proveedores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proveedores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proveedores.
   */
  distinct?: Prisma.ProveedoresScalarFieldEnum | Prisma.ProveedoresScalarFieldEnum[]
}

/**
 * Proveedores findMany
 */
export type ProveedoresFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * Filter, which Proveedores to fetch.
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proveedores to fetch.
   */
  orderBy?: Prisma.ProveedoresOrderByWithRelationInput | Prisma.ProveedoresOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Proveedores.
   */
  cursor?: Prisma.ProveedoresWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proveedores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proveedores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proveedores.
   */
  distinct?: Prisma.ProveedoresScalarFieldEnum | Prisma.ProveedoresScalarFieldEnum[]
}

/**
 * Proveedores create
 */
export type ProveedoresCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * The data needed to create a Proveedores.
   */
  data: Prisma.XOR<Prisma.ProveedoresCreateInput, Prisma.ProveedoresUncheckedCreateInput>
}

/**
 * Proveedores createMany
 */
export type ProveedoresCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Proveedores.
   */
  data: Prisma.ProveedoresCreateManyInput | Prisma.ProveedoresCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Proveedores createManyAndReturn
 */
export type ProveedoresCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * The data used to create many Proveedores.
   */
  data: Prisma.ProveedoresCreateManyInput | Prisma.ProveedoresCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Proveedores update
 */
export type ProveedoresUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * The data needed to update a Proveedores.
   */
  data: Prisma.XOR<Prisma.ProveedoresUpdateInput, Prisma.ProveedoresUncheckedUpdateInput>
  /**
   * Choose, which Proveedores to update.
   */
  where: Prisma.ProveedoresWhereUniqueInput
}

/**
 * Proveedores updateMany
 */
export type ProveedoresUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Proveedores.
   */
  data: Prisma.XOR<Prisma.ProveedoresUpdateManyMutationInput, Prisma.ProveedoresUncheckedUpdateManyInput>
  /**
   * Filter which Proveedores to update
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * Limit how many Proveedores to update.
   */
  limit?: number
}

/**
 * Proveedores updateManyAndReturn
 */
export type ProveedoresUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * The data used to update Proveedores.
   */
  data: Prisma.XOR<Prisma.ProveedoresUpdateManyMutationInput, Prisma.ProveedoresUncheckedUpdateManyInput>
  /**
   * Filter which Proveedores to update
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * Limit how many Proveedores to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Proveedores upsert
 */
export type ProveedoresUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * The filter to search for the Proveedores to update in case it exists.
   */
  where: Prisma.ProveedoresWhereUniqueInput
  /**
   * In case the Proveedores found by the `where` argument doesn't exist, create a new Proveedores with this data.
   */
  create: Prisma.XOR<Prisma.ProveedoresCreateInput, Prisma.ProveedoresUncheckedCreateInput>
  /**
   * In case the Proveedores was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProveedoresUpdateInput, Prisma.ProveedoresUncheckedUpdateInput>
}

/**
 * Proveedores delete
 */
export type ProveedoresDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
  /**
   * Filter which Proveedores to delete.
   */
  where: Prisma.ProveedoresWhereUniqueInput
}

/**
 * Proveedores deleteMany
 */
export type ProveedoresDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proveedores to delete
   */
  where?: Prisma.ProveedoresWhereInput
  /**
   * Limit how many Proveedores to delete.
   */
  limit?: number
}

/**
 * Proveedores.ofertas
 */
export type Proveedores$ofertasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfertaLibro
   */
  select?: Prisma.OfertaLibroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfertaLibro
   */
  omit?: Prisma.OfertaLibroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfertaLibroInclude<ExtArgs> | null
  where?: Prisma.OfertaLibroWhereInput
  orderBy?: Prisma.OfertaLibroOrderByWithRelationInput | Prisma.OfertaLibroOrderByWithRelationInput[]
  cursor?: Prisma.OfertaLibroWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OfertaLibroScalarFieldEnum | Prisma.OfertaLibroScalarFieldEnum[]
}

/**
 * Proveedores without action
 */
export type ProveedoresDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proveedores
   */
  select?: Prisma.ProveedoresSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proveedores
   */
  omit?: Prisma.ProveedoresOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProveedoresInclude<ExtArgs> | null
}
