
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Administradores'
export type * from './models/Compradores'
export type * from './models/Libros'
export type * from './models/LibroDigitalAdquirido'
export type * from './models/Proveedores'
export type * from './models/TiposUsuario'
export type * from './models/ListaProveedor'
export type * from './models/Usuarios'
export type * from './models/OfertaLibro'
export type * from './models/Carritos'
export type * from './models/DetallesCarrito'
export type * from './models/Transacciones'
export type * from './models/DetalleTransaccion'
export type * from './commonInputTypes'