import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../src/prisma/client.js';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
    await prisma.tiposUsuario.createMany({
        data: [
            { nombre: 'ADMIN' },
            { nombre: 'PROVEEDOR' },
            { nombre: 'COMPRADOR' },
            { nombre: 'INACTIVO' },
        ],
        skipDuplicates: true,
    });

    const tipoAdmin = await prisma.tiposUsuario.findFirst({ where: { nombre: 'ADMIN' } });

    await prisma.usuarios.upsert({
        where: { email: 'admin@libreria.com' },
        update: {},
        create: {
            email: 'admin@libreria.com',
            contrasena: 'Admin1234',
            nombre: 'Admin',
            apellido: 'Sistema',
            direccion: 'Sin dirección',
            tipo_usuario_id: tipoAdmin!.id,
            Administradores: { create: {} },
        },
    });

    await prisma.libros.createMany({
        data: [
            {
                isbn: '978-0-14-043205-3',
                nombre: 'El origen de las especies',
                autor: 'Charles Darwin',
                precio: '21900.00',
                stock: 8,
                estado: 'DISPONIBLE',
                archivoDigital: 'TeoriaEvolucion-Darwin.pdf',
                sinopsis: 'La obra fundamental de Charles Darwin donde expone la teoria de la evolucion por seleccion natural, publicada originalmente en 1859.',
                imagenUrl: null,
                categoria: 'HISTORIA',
            },
            {
                isbn: '978-0-14-028329-7',
                nombre: 'Las aventuras de Tom Sawyer',
                autor: 'Mark Twain',
                precio: '15900.00',
                stock: 10,
                estado: 'DISPONIBLE',
                archivoDigital: 'TomSawyer-Twain.pdf',
                sinopsis: 'La vida de Tom Sawyer, un nino travieso que vive a orillas del rio Misisipi en el siglo XIX. Junto a su amigo Huckleberry Finn vive aventuras inolvidables.',
                imagenUrl: null,
                categoria: 'FICCION',
            },
            {
                isbn: '978-84-376-0494-7',
                nombre: 'Odisea',
                autor: 'Homero',
                precio: '16900.00',
                stock: 10,
                estado: 'DISPONIBLE',
                archivoDigital: 'Odisea-Homero.pdf',
                sinopsis: 'El regreso del heroe Odiseo a Itaca tras la guerra de Troya. Durante diez anios enfrenta monstruos, hechiceras y tormentas enviadas por los dioses.',
                imagenUrl: null,
                categoria: 'HISTORIA',
            },
            {
                isbn: '978-84-376-0220-2',
                nombre: 'El fantasma de Canterville',
                autor: 'Oscar Wilde',
                precio: '11900.00',
                stock: 10,
                estado: 'DISPONIBLE',
                archivoDigital: 'FantasmaCanterville-Wilde.pdf',
                sinopsis: 'Una familia americana se muda a un castillo ingles habitado por un fantasma. Los nuevos inquilinos tratan al espectro con indiferencia, con humor e ironia.',
                imagenUrl: null,
                categoria: 'FICCION',
            },
            {
                isbn: '9789875666475',
                nombre: 'El tunel',
                autor: 'Ernesto Sabato',
                precio: '12900.00',
                stock: 18,
                estado: 'DISPONIBLE',
                sinopsis: 'Una novela breve e intensa sobre la obsesion, la soledad y los limites de la razon.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9789875666475-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9789507315109',
                nombre: 'Rayuela',
                autor: 'Julio Cortazar',
                precio: '18900.00',
                stock: 12,
                estado: 'DISPONIBLE',
                sinopsis: 'Una obra experimental que invita a recorrer Paris y Buenos Aires entre juegos literarios y busquedas existenciales.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9789507315109-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9780307474728',
                nombre: 'Cien anos de soledad',
                autor: 'Gabriel Garcia Marquez',
                precio: '21500.00',
                stock: 15,
                estado: 'DISPONIBLE',
                sinopsis: 'La historia de los Buendia y Macondo, atravesada por generaciones, mitos familiares y realismo magico.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780307474728-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9788497592208',
                nombre: 'La sombra del viento',
                autor: 'Carlos Ruiz Zafon',
                precio: '20500.00',
                stock: 10,
                estado: 'DISPONIBLE',
                sinopsis: 'Un misterio literario ambientado en Barcelona, donde un libro olvidado cambia la vida de su lector.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9788497592208-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9780061120084',
                nombre: 'Matar a un ruisenor',
                autor: 'Harper Lee',
                precio: '17600.00',
                stock: 9,
                estado: 'DISPONIBLE',
                sinopsis: 'Una mirada sensible sobre la justicia, la infancia y los prejuicios en el sur de Estados Unidos.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9780451524935',
                nombre: '1984',
                autor: 'George Orwell',
                precio: '14800.00',
                stock: 20,
                estado: 'DISPONIBLE',
                sinopsis: 'Una distopia sobre vigilancia, manipulacion politica y resistencia individual.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9780544003415',
                nombre: 'El hobbit',
                autor: 'J. R. R. Tolkien',
                precio: '23200.00',
                stock: 14,
                estado: 'DISPONIBLE',
                sinopsis: 'Bilbo Bolson inicia una aventura inesperada con enanos, mapas secretos y un dragon.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg',
                categoria: 'FANTASIA',
            },
            {
                isbn: '9788478884452',
                nombre: 'Harry Potter y la piedra filosofal',
                autor: 'J. K. Rowling',
                precio: '19800.00',
                stock: 16,
                estado: 'DISPONIBLE',
                sinopsis: 'Un joven descubre su lugar en el mundo magico y comienza sus estudios en Hogwarts.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9788478884452-L.jpg',
                categoria: 'FANTASIA',
            },
            {
                isbn: '9780553573404',
                nombre: 'Juego de tronos',
                autor: 'George R. R. Martin',
                precio: '25500.00',
                stock: 8,
                estado: 'DISPONIBLE',
                sinopsis: 'Intrigas, alianzas y traiciones marcan la lucha por el poder en los Siete Reinos.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780553573404-L.jpg',
                categoria: 'FANTASIA',
            },
            {
                isbn: '9788498383621',
                nombre: 'El nombre del viento',
                autor: 'Patrick Rothfuss',
                precio: '23900.00',
                stock: 11,
                estado: 'DISPONIBLE',
                sinopsis: 'Kvothe relata su vida entre musica, magia, universidad y leyenda.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9788498383621-L.jpg',
                categoria: 'FANTASIA',
            },
            {
                isbn: '9780307743657',
                nombre: 'El resplandor',
                autor: 'Stephen King',
                precio: '22100.00',
                stock: 7,
                estado: 'DISPONIBLE',
                sinopsis: 'Una familia aislada en un hotel de montana enfrenta fuerzas oscuras y una mente que se quiebra.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780307743657-L.jpg',
                categoria: 'TERROR',
            },
            {
                isbn: '9780141439846',
                nombre: 'Frankenstein',
                autor: 'Mary Shelley',
                precio: '14200.00',
                stock: 13,
                estado: 'DISPONIBLE',
                sinopsis: 'Un cientifico da vida a una criatura y debe enfrentar las consecuencias de su ambicion.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg',
                categoria: 'TERROR',
            },
            {
                isbn: '9780141439563',
                nombre: 'Dracula',
                autor: 'Bram Stoker',
                precio: '15100.00',
                stock: 10,
                estado: 'DISPONIBLE',
                sinopsis: 'Cartas y diarios revelan el avance del conde Dracula y la lucha por detenerlo.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg',
                categoria: 'TERROR',
            },
            {
                isbn: '9780307277671',
                nombre: 'La carretera',
                autor: 'Cormac McCarthy',
                precio: '18400.00',
                stock: 6,
                estado: 'DISPONIBLE',
                sinopsis: 'Un padre y su hijo atraviesan un mundo devastado buscando esperanza y supervivencia.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780307277671-L.jpg',
                categoria: 'FICCION',
            },
            {
                isbn: '9780307389732',
                nombre: 'Sapiens',
                autor: 'Yuval Noah Harari',
                precio: '27800.00',
                stock: 17,
                estado: 'DISPONIBLE',
                sinopsis: 'Un recorrido por la historia humana desde los primeros sapiens hasta las sociedades modernas.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780307389732-L.jpg',
                categoria: 'HISTORIA',
            },
            {
                isbn: '9788426416217',
                nombre: 'El diario de Ana Frank',
                autor: 'Ana Frank',
                precio: '13700.00',
                stock: 19,
                estado: 'DISPONIBLE',
                sinopsis: 'El testimonio de una adolescente escondida durante la ocupacion nazi en Amsterdam.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9788426416217-L.jpg',
                categoria: 'HISTORIA',
            },
            {
                isbn: '9780805047905',
                nombre: 'Brown Bear, Brown Bear, What Do You See?',
                autor: 'Bill Martin Jr. y Eric Carle',
                precio: '9800.00',
                stock: 22,
                estado: 'DISPONIBLE',
                sinopsis: 'Un clasico infantil de lectura simple, ritmo repetitivo y colores vivos.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780805047905-L.jpg',
                categoria: 'INFANTIL',
            },
            {
                isbn: '9780064431781',
                nombre: 'The Very Hungry Caterpillar',
                autor: 'Eric Carle',
                precio: '10200.00',
                stock: 21,
                estado: 'DISPONIBLE',
                sinopsis: 'Un cuento infantil sobre crecimiento, comida y transformacion.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780064431781-L.jpg',
                categoria: 'INFANTIL',
            },
            {
                isbn: '9788498387087',
                nombre: 'El principito',
                autor: 'Antoine de Saint-Exupery',
                precio: '11900.00',
                stock: 24,
                estado: 'DISPONIBLE',
                sinopsis: 'Una fabula poetica sobre la amistad, la mirada adulta y lo esencial.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9788498387087-L.jpg',
                categoria: 'INFANTIL',
            },
            {
                isbn: '9780140449136',
                nombre: 'La odisea',
                autor: 'Homero',
                precio: '16200.00',
                stock: 9,
                estado: 'DISPONIBLE',
                sinopsis: 'El viaje de Odiseo de regreso a Itaca despues de la guerra de Troya.',
                imagenUrl: 'https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg',
                categoria: 'GENERAL',
            },
        ],
        skipDuplicates: true,
    });
}

main()
    .catch((e) => { console.error(e); process.exit(1); })
    .finally(() => prisma.$disconnect());
