
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Libros` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Libros
 * 
 */
export type LibrosModel = runtime.Types.Result.DefaultSelection<Prisma.$LibrosPayload>

export type AggregateLibros = {
  _count: LibrosCountAggregateOutputType | null
  _avg: LibrosAvgAggregateOutputType | null
  _sum: LibrosSumAggregateOutputType | null
  _min: LibrosMinAggregateOutputType | null
  _max: LibrosMaxAggregateOutputType | null
}

export type LibrosAvgAggregateOutputType = {
  id: number | null
  precio: runtime.Decimal | null
  stock: number | null
}

export type LibrosSumAggregateOutputType = {
  id: number | null
  precio: runtime.Decimal | null
  stock: number | null
}

export type LibrosMinAggregateOutputType = {
  id: number | null
  isbn: string | null
  nombre: string | null
  autor: string | null
  precio: runtime.Decimal | null
  stock: number | null
  estado: string | null
  archivoDigital: string | null
  sinopsis: string | null
  imagenUrl: string | null
  categoria: $Enums.CategoriaLibro | null
}

export type LibrosMaxAggregateOutputType = {
  id: number | null
  isbn: string | null
  nombre: string | null
  autor: string | null
  precio: runtime.Decimal | null
  stock: number | null
  estado: string | null
  archivoDigital: string | null
  sinopsis: string | null
  imagenUrl: string | null
  categoria: $Enums.CategoriaLibro | null
}

export type LibrosCountAggregateOutputType = {
  id: number
  isbn: number
  nombre: number
  autor: number
  precio: number
  stock: number
  estado: number
  archivoDigital: number
  sinopsis: number
  imagenUrl: number
  categoria: number
  _all: number
}


export type LibrosAvgAggregateInputType = {
  id?: true
  precio?: true
  stock?: true
}

export type LibrosSumAggregateInputType = {
  id?: true
  precio?: true
  stock?: true
}

export type LibrosMinAggregateInputType = {
  id?: true
  isbn?: true
  nombre?: true
  autor?: true
  precio?: true
  stock?: true
  estado?: true
  archivoDigital?: true
  sinopsis?: true
  imagenUrl?: true
  categoria?: true
}

export type LibrosMaxAggregateInputType = {
  id?: true
  isbn?: true
  nombre?: true
  autor?: true
  precio?: true
  stock?: true
  estado?: true
  archivoDigital?: true
  sinopsis?: true
  imagenUrl?: true
  categoria?: true
}

export type LibrosCountAggregateInputType = {
  id?: true
  isbn?: true
  nombre?: true
  autor?: true
  precio?: true
  stock?: true
  estado?: true
  archivoDigital?: true
  sinopsis?: true
  imagenUrl?: true
  categoria?: true
  _all?: true
}

export type LibrosAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Libros to aggregate.
   */
  where?: Prisma.LibrosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Libros to fetch.
   */
  orderBy?: Prisma.LibrosOrderByWithRelationInput | Prisma.LibrosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LibrosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Libros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Libros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Libros
  **/
  _count?: true | LibrosCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LibrosAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LibrosSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LibrosMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LibrosMaxAggregateInputType
}

export type GetLibrosAggregateType<T extends LibrosAggregateArgs> = {
      [P in keyof T & keyof AggregateLibros]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLibros[P]>
    : Prisma.GetScalarType<T[P], AggregateLibros[P]>
}




export type LibrosGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LibrosWhereInput
  orderBy?: Prisma.LibrosOrderByWithAggregationInput | Prisma.LibrosOrderByWithAggregationInput[]
  by: Prisma.LibrosScalarFieldEnum[] | Prisma.LibrosScalarFieldEnum
  having?: Prisma.LibrosScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LibrosCountAggregateInputType | true
  _avg?: LibrosAvgAggregateInputType
  _sum?: LibrosSumAggregateInputType
  _min?: LibrosMinAggregateInputType
  _max?: LibrosMaxAggregateInputType
}

export type LibrosGroupByOutputType = {
  id: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal
  stock: number | null
  estado: string | null
  archivoDigital: string | null
  sinopsis: string | null
  imagenUrl: string | null
  categoria: $Enums.CategoriaLibro
  _count: LibrosCountAggregateOutputType | null
  _avg: LibrosAvgAggregateOutputType | null
  _sum: LibrosSumAggregateOutputType | null
  _min: LibrosMinAggregateOutputType | null
  _max: LibrosMaxAggregateOutputType | null
}

export type GetLibrosGroupByPayload<T extends LibrosGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LibrosGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LibrosGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LibrosGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LibrosGroupByOutputType[P]>
      }
    >
  >



export type LibrosWhereInput = {
  AND?: Prisma.LibrosWhereInput | Prisma.LibrosWhereInput[]
  OR?: Prisma.LibrosWhereInput[]
  NOT?: Prisma.LibrosWhereInput | Prisma.LibrosWhereInput[]
  id?: Prisma.IntFilter<"Libros"> | number
  isbn?: Prisma.StringFilter<"Libros"> | string
  nombre?: Prisma.StringFilter<"Libros"> | string
  autor?: Prisma.StringFilter<"Libros"> | string
  precio?: Prisma.DecimalFilter<"Libros"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.IntNullableFilter<"Libros"> | number | null
  estado?: Prisma.StringNullableFilter<"Libros"> | string | null
  archivoDigital?: Prisma.StringNullableFilter<"Libros"> | string | null
  sinopsis?: Prisma.StringNullableFilter<"Libros"> | string | null
  imagenUrl?: Prisma.StringNullableFilter<"Libros"> | string | null
  categoria?: Prisma.EnumCategoriaLibroFilter<"Libros"> | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionListRelationFilter
  detallesCarritos?: Prisma.DetallesCarritoListRelationFilter
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoListRelationFilter
  ofertas?: Prisma.OfertaLibroListRelationFilter
}

export type LibrosOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrderInput | Prisma.SortOrder
  archivoDigital?: Prisma.SortOrderInput | Prisma.SortOrder
  sinopsis?: Prisma.SortOrderInput | Prisma.SortOrder
  imagenUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  categoria?: Prisma.SortOrder
  detalleTransaccions?: Prisma.DetalleTransaccionOrderByRelationAggregateInput
  detallesCarritos?: Prisma.DetallesCarritoOrderByRelationAggregateInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoOrderByRelationAggregateInput
  ofertas?: Prisma.OfertaLibroOrderByRelationAggregateInput
}

export type LibrosWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  isbn?: string
  AND?: Prisma.LibrosWhereInput | Prisma.LibrosWhereInput[]
  OR?: Prisma.LibrosWhereInput[]
  NOT?: Prisma.LibrosWhereInput | Prisma.LibrosWhereInput[]
  nombre?: Prisma.StringFilter<"Libros"> | string
  autor?: Prisma.StringFilter<"Libros"> | string
  precio?: Prisma.DecimalFilter<"Libros"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.IntNullableFilter<"Libros"> | number | null
  estado?: Prisma.StringNullableFilter<"Libros"> | string | null
  archivoDigital?: Prisma.StringNullableFilter<"Libros"> | string | null
  sinopsis?: Prisma.StringNullableFilter<"Libros"> | string | null
  imagenUrl?: Prisma.StringNullableFilter<"Libros"> | string | null
  categoria?: Prisma.EnumCategoriaLibroFilter<"Libros"> | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionListRelationFilter
  detallesCarritos?: Prisma.DetallesCarritoListRelationFilter
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoListRelationFilter
  ofertas?: Prisma.OfertaLibroListRelationFilter
}, "id" | "isbn">

export type LibrosOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrderInput | Prisma.SortOrder
  archivoDigital?: Prisma.SortOrderInput | Prisma.SortOrder
  sinopsis?: Prisma.SortOrderInput | Prisma.SortOrder
  imagenUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  categoria?: Prisma.SortOrder
  _count?: Prisma.LibrosCountOrderByAggregateInput
  _avg?: Prisma.LibrosAvgOrderByAggregateInput
  _max?: Prisma.LibrosMaxOrderByAggregateInput
  _min?: Prisma.LibrosMinOrderByAggregateInput
  _sum?: Prisma.LibrosSumOrderByAggregateInput
}

export type LibrosScalarWhereWithAggregatesInput = {
  AND?: Prisma.LibrosScalarWhereWithAggregatesInput | Prisma.LibrosScalarWhereWithAggregatesInput[]
  OR?: Prisma.LibrosScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LibrosScalarWhereWithAggregatesInput | Prisma.LibrosScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Libros"> | number
  isbn?: Prisma.StringWithAggregatesFilter<"Libros"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"Libros"> | string
  autor?: Prisma.StringWithAggregatesFilter<"Libros"> | string
  precio?: Prisma.DecimalWithAggregatesFilter<"Libros"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.IntNullableWithAggregatesFilter<"Libros"> | number | null
  estado?: Prisma.StringNullableWithAggregatesFilter<"Libros"> | string | null
  archivoDigital?: Prisma.StringNullableWithAggregatesFilter<"Libros"> | string | null
  sinopsis?: Prisma.StringNullableWithAggregatesFilter<"Libros"> | string | null
  imagenUrl?: Prisma.StringNullableWithAggregatesFilter<"Libros"> | string | null
  categoria?: Prisma.EnumCategoriaLibroWithAggregatesFilter<"Libros"> | $Enums.CategoriaLibro
}

export type LibrosCreateInput = {
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionCreateNestedManyWithoutLibroInput
  detallesCarritos?: Prisma.DetallesCarritoCreateNestedManyWithoutLibrosInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroCreateNestedManyWithoutLibroInput
}

export type LibrosUncheckedCreateInput = {
  id?: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedCreateNestedManyWithoutLibroInput
  detallesCarritos?: Prisma.DetallesCarritoUncheckedCreateNestedManyWithoutLibrosInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroUncheckedCreateNestedManyWithoutLibroInput
}

export type LibrosUpdateInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUpdateManyWithoutLibroNestedInput
  detallesCarritos?: Prisma.DetallesCarritoUpdateManyWithoutLibrosNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUpdateManyWithoutLibroNestedInput
}

export type LibrosUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedUpdateManyWithoutLibroNestedInput
  detallesCarritos?: Prisma.DetallesCarritoUncheckedUpdateManyWithoutLibrosNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUncheckedUpdateManyWithoutLibroNestedInput
}

export type LibrosCreateManyInput = {
  id?: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
}

export type LibrosUpdateManyMutationInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
}

export type LibrosUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
}

export type LibrosCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  archivoDigital?: Prisma.SortOrder
  sinopsis?: Prisma.SortOrder
  imagenUrl?: Prisma.SortOrder
  categoria?: Prisma.SortOrder
}

export type LibrosAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrder
}

export type LibrosMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  archivoDigital?: Prisma.SortOrder
  sinopsis?: Prisma.SortOrder
  imagenUrl?: Prisma.SortOrder
  categoria?: Prisma.SortOrder
}

export type LibrosMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isbn?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  archivoDigital?: Prisma.SortOrder
  sinopsis?: Prisma.SortOrder
  imagenUrl?: Prisma.SortOrder
  categoria?: Prisma.SortOrder
}

export type LibrosSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  precio?: Prisma.SortOrder
  stock?: Prisma.SortOrder
}

export type LibrosScalarRelationFilter = {
  is?: Prisma.LibrosWhereInput
  isNot?: Prisma.LibrosWhereInput
}

export type LibrosNullableScalarRelationFilter = {
  is?: Prisma.LibrosWhereInput | null
  isNot?: Prisma.LibrosWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumCategoriaLibroFieldUpdateOperationsInput = {
  set?: $Enums.CategoriaLibro
}

export type LibrosCreateNestedOneWithoutLibrosDigitalesAdquiridosInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutLibrosDigitalesAdquiridosInput
  connect?: Prisma.LibrosWhereUniqueInput
}

export type LibrosUpdateOneRequiredWithoutLibrosDigitalesAdquiridosNestedInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutLibrosDigitalesAdquiridosInput
  upsert?: Prisma.LibrosUpsertWithoutLibrosDigitalesAdquiridosInput
  connect?: Prisma.LibrosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LibrosUpdateToOneWithWhereWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUpdateWithoutLibrosDigitalesAdquiridosInput>, Prisma.LibrosUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput>
}

export type LibrosCreateNestedOneWithoutOfertasInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutOfertasInput, Prisma.LibrosUncheckedCreateWithoutOfertasInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutOfertasInput
  connect?: Prisma.LibrosWhereUniqueInput
}

export type LibrosUpdateOneWithoutOfertasNestedInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutOfertasInput, Prisma.LibrosUncheckedCreateWithoutOfertasInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutOfertasInput
  upsert?: Prisma.LibrosUpsertWithoutOfertasInput
  disconnect?: Prisma.LibrosWhereInput | boolean
  delete?: Prisma.LibrosWhereInput | boolean
  connect?: Prisma.LibrosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LibrosUpdateToOneWithWhereWithoutOfertasInput, Prisma.LibrosUpdateWithoutOfertasInput>, Prisma.LibrosUncheckedUpdateWithoutOfertasInput>
}

export type LibrosCreateNestedOneWithoutDetallesCarritosInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutDetallesCarritosInput, Prisma.LibrosUncheckedCreateWithoutDetallesCarritosInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutDetallesCarritosInput
  connect?: Prisma.LibrosWhereUniqueInput
}

export type LibrosUpdateOneRequiredWithoutDetallesCarritosNestedInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutDetallesCarritosInput, Prisma.LibrosUncheckedCreateWithoutDetallesCarritosInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutDetallesCarritosInput
  upsert?: Prisma.LibrosUpsertWithoutDetallesCarritosInput
  connect?: Prisma.LibrosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LibrosUpdateToOneWithWhereWithoutDetallesCarritosInput, Prisma.LibrosUpdateWithoutDetallesCarritosInput>, Prisma.LibrosUncheckedUpdateWithoutDetallesCarritosInput>
}

export type LibrosCreateNestedOneWithoutDetalleTransaccionsInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutDetalleTransaccionsInput, Prisma.LibrosUncheckedCreateWithoutDetalleTransaccionsInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutDetalleTransaccionsInput
  connect?: Prisma.LibrosWhereUniqueInput
}

export type LibrosUpdateOneRequiredWithoutDetalleTransaccionsNestedInput = {
  create?: Prisma.XOR<Prisma.LibrosCreateWithoutDetalleTransaccionsInput, Prisma.LibrosUncheckedCreateWithoutDetalleTransaccionsInput>
  connectOrCreate?: Prisma.LibrosCreateOrConnectWithoutDetalleTransaccionsInput
  upsert?: Prisma.LibrosUpsertWithoutDetalleTransaccionsInput
  connect?: Prisma.LibrosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LibrosUpdateToOneWithWhereWithoutDetalleTransaccionsInput, Prisma.LibrosUpdateWithoutDetalleTransaccionsInput>, Prisma.LibrosUncheckedUpdateWithoutDetalleTransaccionsInput>
}

export type LibrosCreateWithoutLibrosDigitalesAdquiridosInput = {
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionCreateNestedManyWithoutLibroInput
  detallesCarritos?: Prisma.DetallesCarritoCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroCreateNestedManyWithoutLibroInput
}

export type LibrosUncheckedCreateWithoutLibrosDigitalesAdquiridosInput = {
  id?: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedCreateNestedManyWithoutLibroInput
  detallesCarritos?: Prisma.DetallesCarritoUncheckedCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroUncheckedCreateNestedManyWithoutLibroInput
}

export type LibrosCreateOrConnectWithoutLibrosDigitalesAdquiridosInput = {
  where: Prisma.LibrosWhereUniqueInput
  create: Prisma.XOR<Prisma.LibrosCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
}

export type LibrosUpsertWithoutLibrosDigitalesAdquiridosInput = {
  update: Prisma.XOR<Prisma.LibrosUpdateWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput>
  create: Prisma.XOR<Prisma.LibrosCreateWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUncheckedCreateWithoutLibrosDigitalesAdquiridosInput>
  where?: Prisma.LibrosWhereInput
}

export type LibrosUpdateToOneWithWhereWithoutLibrosDigitalesAdquiridosInput = {
  where?: Prisma.LibrosWhereInput
  data: Prisma.XOR<Prisma.LibrosUpdateWithoutLibrosDigitalesAdquiridosInput, Prisma.LibrosUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput>
}

export type LibrosUpdateWithoutLibrosDigitalesAdquiridosInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUpdateManyWithoutLibroNestedInput
  detallesCarritos?: Prisma.DetallesCarritoUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUpdateManyWithoutLibroNestedInput
}

export type LibrosUncheckedUpdateWithoutLibrosDigitalesAdquiridosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedUpdateManyWithoutLibroNestedInput
  detallesCarritos?: Prisma.DetallesCarritoUncheckedUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUncheckedUpdateManyWithoutLibroNestedInput
}

export type LibrosCreateWithoutOfertasInput = {
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionCreateNestedManyWithoutLibroInput
  detallesCarritos?: Prisma.DetallesCarritoCreateNestedManyWithoutLibrosInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutLibrosInput
}

export type LibrosUncheckedCreateWithoutOfertasInput = {
  id?: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedCreateNestedManyWithoutLibroInput
  detallesCarritos?: Prisma.DetallesCarritoUncheckedCreateNestedManyWithoutLibrosInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutLibrosInput
}

export type LibrosCreateOrConnectWithoutOfertasInput = {
  where: Prisma.LibrosWhereUniqueInput
  create: Prisma.XOR<Prisma.LibrosCreateWithoutOfertasInput, Prisma.LibrosUncheckedCreateWithoutOfertasInput>
}

export type LibrosUpsertWithoutOfertasInput = {
  update: Prisma.XOR<Prisma.LibrosUpdateWithoutOfertasInput, Prisma.LibrosUncheckedUpdateWithoutOfertasInput>
  create: Prisma.XOR<Prisma.LibrosCreateWithoutOfertasInput, Prisma.LibrosUncheckedCreateWithoutOfertasInput>
  where?: Prisma.LibrosWhereInput
}

export type LibrosUpdateToOneWithWhereWithoutOfertasInput = {
  where?: Prisma.LibrosWhereInput
  data: Prisma.XOR<Prisma.LibrosUpdateWithoutOfertasInput, Prisma.LibrosUncheckedUpdateWithoutOfertasInput>
}

export type LibrosUpdateWithoutOfertasInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUpdateManyWithoutLibroNestedInput
  detallesCarritos?: Prisma.DetallesCarritoUpdateManyWithoutLibrosNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutLibrosNestedInput
}

export type LibrosUncheckedUpdateWithoutOfertasInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedUpdateManyWithoutLibroNestedInput
  detallesCarritos?: Prisma.DetallesCarritoUncheckedUpdateManyWithoutLibrosNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutLibrosNestedInput
}

export type LibrosCreateWithoutDetallesCarritosInput = {
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionCreateNestedManyWithoutLibroInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroCreateNestedManyWithoutLibroInput
}

export type LibrosUncheckedCreateWithoutDetallesCarritosInput = {
  id?: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedCreateNestedManyWithoutLibroInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroUncheckedCreateNestedManyWithoutLibroInput
}

export type LibrosCreateOrConnectWithoutDetallesCarritosInput = {
  where: Prisma.LibrosWhereUniqueInput
  create: Prisma.XOR<Prisma.LibrosCreateWithoutDetallesCarritosInput, Prisma.LibrosUncheckedCreateWithoutDetallesCarritosInput>
}

export type LibrosUpsertWithoutDetallesCarritosInput = {
  update: Prisma.XOR<Prisma.LibrosUpdateWithoutDetallesCarritosInput, Prisma.LibrosUncheckedUpdateWithoutDetallesCarritosInput>
  create: Prisma.XOR<Prisma.LibrosCreateWithoutDetallesCarritosInput, Prisma.LibrosUncheckedCreateWithoutDetallesCarritosInput>
  where?: Prisma.LibrosWhereInput
}

export type LibrosUpdateToOneWithWhereWithoutDetallesCarritosInput = {
  where?: Prisma.LibrosWhereInput
  data: Prisma.XOR<Prisma.LibrosUpdateWithoutDetallesCarritosInput, Prisma.LibrosUncheckedUpdateWithoutDetallesCarritosInput>
}

export type LibrosUpdateWithoutDetallesCarritosInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUpdateManyWithoutLibroNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUpdateManyWithoutLibroNestedInput
}

export type LibrosUncheckedUpdateWithoutDetallesCarritosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detalleTransaccions?: Prisma.DetalleTransaccionUncheckedUpdateManyWithoutLibroNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUncheckedUpdateManyWithoutLibroNestedInput
}

export type LibrosCreateWithoutDetalleTransaccionsInput = {
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detallesCarritos?: Prisma.DetallesCarritoCreateNestedManyWithoutLibrosInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroCreateNestedManyWithoutLibroInput
}

export type LibrosUncheckedCreateWithoutDetalleTransaccionsInput = {
  id?: number
  isbn: string
  nombre: string
  autor: string
  precio: runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: number | null
  estado?: string | null
  archivoDigital?: string | null
  sinopsis?: string | null
  imagenUrl?: string | null
  categoria?: $Enums.CategoriaLibro
  detallesCarritos?: Prisma.DetallesCarritoUncheckedCreateNestedManyWithoutLibrosInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedCreateNestedManyWithoutLibrosInput
  ofertas?: Prisma.OfertaLibroUncheckedCreateNestedManyWithoutLibroInput
}

export type LibrosCreateOrConnectWithoutDetalleTransaccionsInput = {
  where: Prisma.LibrosWhereUniqueInput
  create: Prisma.XOR<Prisma.LibrosCreateWithoutDetalleTransaccionsInput, Prisma.LibrosUncheckedCreateWithoutDetalleTransaccionsInput>
}

export type LibrosUpsertWithoutDetalleTransaccionsInput = {
  update: Prisma.XOR<Prisma.LibrosUpdateWithoutDetalleTransaccionsInput, Prisma.LibrosUncheckedUpdateWithoutDetalleTransaccionsInput>
  create: Prisma.XOR<Prisma.LibrosCreateWithoutDetalleTransaccionsInput, Prisma.LibrosUncheckedCreateWithoutDetalleTransaccionsInput>
  where?: Prisma.LibrosWhereInput
}

export type LibrosUpdateToOneWithWhereWithoutDetalleTransaccionsInput = {
  where?: Prisma.LibrosWhereInput
  data: Prisma.XOR<Prisma.LibrosUpdateWithoutDetalleTransaccionsInput, Prisma.LibrosUncheckedUpdateWithoutDetalleTransaccionsInput>
}

export type LibrosUpdateWithoutDetalleTransaccionsInput = {
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detallesCarritos?: Prisma.DetallesCarritoUpdateManyWithoutLibrosNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUpdateManyWithoutLibroNestedInput
}

export type LibrosUncheckedUpdateWithoutDetalleTransaccionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  isbn?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  precio?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  estado?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archivoDigital?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sinopsis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imagenUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoria?: Prisma.EnumCategoriaLibroFieldUpdateOperationsInput | $Enums.CategoriaLibro
  detallesCarritos?: Prisma.DetallesCarritoUncheckedUpdateManyWithoutLibrosNestedInput
  LibrosDigitalesAdquiridos?: Prisma.LibroDigitalAdquiridoUncheckedUpdateManyWithoutLibrosNestedInput
  ofertas?: Prisma.OfertaLibroUncheckedUpdateManyWithoutLibroNestedInput
}


/**
 * Count Type LibrosCountOutputType
 */

export type LibrosCountOutputType = {
  detalleTransaccions: number
  detallesCarritos: number
  LibrosDigitalesAdquiridos: number
  ofertas: number
}

export type LibrosCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  detalleTransaccions?: boolean | LibrosCountOutputTypeCountDetalleTransaccionsArgs
  detallesCarritos?: boolean | LibrosCountOutputTypeCountDetallesCarritosArgs
  LibrosDigitalesAdquiridos?: boolean | LibrosCountOutputTypeCountLibrosDigitalesAdquiridosArgs
  ofertas?: boolean | LibrosCountOutputTypeCountOfertasArgs
}

/**
 * LibrosCountOutputType without action
 */
export type LibrosCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibrosCountOutputType
   */
  select?: Prisma.LibrosCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LibrosCountOutputType without action
 */
export type LibrosCountOutputTypeCountDetalleTransaccionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DetalleTransaccionWhereInput
}

/**
 * LibrosCountOutputType without action
 */
export type LibrosCountOutputTypeCountDetallesCarritosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DetallesCarritoWhereInput
}

/**
 * LibrosCountOutputType without action
 */
export type LibrosCountOutputTypeCountLibrosDigitalesAdquiridosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LibroDigitalAdquiridoWhereInput
}

/**
 * LibrosCountOutputType without action
 */
export type LibrosCountOutputTypeCountOfertasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfertaLibroWhereInput
}


export type LibrosSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isbn?: boolean
  nombre?: boolean
  autor?: boolean
  precio?: boolean
  stock?: boolean
  estado?: boolean
  archivoDigital?: boolean
  sinopsis?: boolean
  imagenUrl?: boolean
  categoria?: boolean
  detalleTransaccions?: boolean | Prisma.Libros$detalleTransaccionsArgs<ExtArgs>
  detallesCarritos?: boolean | Prisma.Libros$detallesCarritosArgs<ExtArgs>
  LibrosDigitalesAdquiridos?: boolean | Prisma.Libros$LibrosDigitalesAdquiridosArgs<ExtArgs>
  ofertas?: boolean | Prisma.Libros$ofertasArgs<ExtArgs>
  _count?: boolean | Prisma.LibrosCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["libros"]>

export type LibrosSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isbn?: boolean
  nombre?: boolean
  autor?: boolean
  precio?: boolean
  stock?: boolean
  estado?: boolean
  archivoDigital?: boolean
  sinopsis?: boolean
  imagenUrl?: boolean
  categoria?: boolean
}, ExtArgs["result"]["libros"]>

export type LibrosSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isbn?: boolean
  nombre?: boolean
  autor?: boolean
  precio?: boolean
  stock?: boolean
  estado?: boolean
  archivoDigital?: boolean
  sinopsis?: boolean
  imagenUrl?: boolean
  categoria?: boolean
}, ExtArgs["result"]["libros"]>

export type LibrosSelectScalar = {
  id?: boolean
  isbn?: boolean
  nombre?: boolean
  autor?: boolean
  precio?: boolean
  stock?: boolean
  estado?: boolean
  archivoDigital?: boolean
  sinopsis?: boolean
  imagenUrl?: boolean
  categoria?: boolean
}

export type LibrosOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "isbn" | "nombre" | "autor" | "precio" | "stock" | "estado" | "archivoDigital" | "sinopsis" | "imagenUrl" | "categoria", ExtArgs["result"]["libros"]>
export type LibrosInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  detalleTransaccions?: boolean | Prisma.Libros$detalleTransaccionsArgs<ExtArgs>
  detallesCarritos?: boolean | Prisma.Libros$detallesCarritosArgs<ExtArgs>
  LibrosDigitalesAdquiridos?: boolean | Prisma.Libros$LibrosDigitalesAdquiridosArgs<ExtArgs>
  ofertas?: boolean | Prisma.Libros$ofertasArgs<ExtArgs>
  _count?: boolean | Prisma.LibrosCountOutputTypeDefaultArgs<ExtArgs>
}
export type LibrosIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type LibrosIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $LibrosPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Libros"
  objects: {
    detalleTransaccions: Prisma.$DetalleTransaccionPayload<ExtArgs>[]
    detallesCarritos: Prisma.$DetallesCarritoPayload<ExtArgs>[]
    LibrosDigitalesAdquiridos: Prisma.$LibroDigitalAdquiridoPayload<ExtArgs>[]
    ofertas: Prisma.$OfertaLibroPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    isbn: string
    nombre: string
    autor: string
    precio: runtime.Decimal
    stock: number | null
    estado: string | null
    archivoDigital: string | null
    sinopsis: string | null
    imagenUrl: string | null
    categoria: $Enums.CategoriaLibro
  }, ExtArgs["result"]["libros"]>
  composites: {}
}

export type LibrosGetPayload<S extends boolean | null | undefined | LibrosDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LibrosPayload, S>

export type LibrosCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LibrosFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LibrosCountAggregateInputType | true
  }

export interface LibrosDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Libros'], meta: { name: 'Libros' } }
  /**
   * Find zero or one Libros that matches the filter.
   * @param {LibrosFindUniqueArgs} args - Arguments to find a Libros
   * @example
   * // Get one Libros
   * const libros = await prisma.libros.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LibrosFindUniqueArgs>(args: Prisma.SelectSubset<T, LibrosFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Libros that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LibrosFindUniqueOrThrowArgs} args - Arguments to find a Libros
   * @example
   * // Get one Libros
   * const libros = await prisma.libros.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LibrosFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LibrosFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Libros that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosFindFirstArgs} args - Arguments to find a Libros
   * @example
   * // Get one Libros
   * const libros = await prisma.libros.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LibrosFindFirstArgs>(args?: Prisma.SelectSubset<T, LibrosFindFirstArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Libros that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosFindFirstOrThrowArgs} args - Arguments to find a Libros
   * @example
   * // Get one Libros
   * const libros = await prisma.libros.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LibrosFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LibrosFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Libros that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Libros
   * const libros = await prisma.libros.findMany()
   * 
   * // Get first 10 Libros
   * const libros = await prisma.libros.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const librosWithIdOnly = await prisma.libros.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LibrosFindManyArgs>(args?: Prisma.SelectSubset<T, LibrosFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Libros.
   * @param {LibrosCreateArgs} args - Arguments to create a Libros.
   * @example
   * // Create one Libros
   * const Libros = await prisma.libros.create({
   *   data: {
   *     // ... data to create a Libros
   *   }
   * })
   * 
   */
  create<T extends LibrosCreateArgs>(args: Prisma.SelectSubset<T, LibrosCreateArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Libros.
   * @param {LibrosCreateManyArgs} args - Arguments to create many Libros.
   * @example
   * // Create many Libros
   * const libros = await prisma.libros.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LibrosCreateManyArgs>(args?: Prisma.SelectSubset<T, LibrosCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Libros and returns the data saved in the database.
   * @param {LibrosCreateManyAndReturnArgs} args - Arguments to create many Libros.
   * @example
   * // Create many Libros
   * const libros = await prisma.libros.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Libros and only return the `id`
   * const librosWithIdOnly = await prisma.libros.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LibrosCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LibrosCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Libros.
   * @param {LibrosDeleteArgs} args - Arguments to delete one Libros.
   * @example
   * // Delete one Libros
   * const Libros = await prisma.libros.delete({
   *   where: {
   *     // ... filter to delete one Libros
   *   }
   * })
   * 
   */
  delete<T extends LibrosDeleteArgs>(args: Prisma.SelectSubset<T, LibrosDeleteArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Libros.
   * @param {LibrosUpdateArgs} args - Arguments to update one Libros.
   * @example
   * // Update one Libros
   * const libros = await prisma.libros.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LibrosUpdateArgs>(args: Prisma.SelectSubset<T, LibrosUpdateArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Libros.
   * @param {LibrosDeleteManyArgs} args - Arguments to filter Libros to delete.
   * @example
   * // Delete a few Libros
   * const { count } = await prisma.libros.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LibrosDeleteManyArgs>(args?: Prisma.SelectSubset<T, LibrosDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Libros.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Libros
   * const libros = await prisma.libros.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LibrosUpdateManyArgs>(args: Prisma.SelectSubset<T, LibrosUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Libros and returns the data updated in the database.
   * @param {LibrosUpdateManyAndReturnArgs} args - Arguments to update many Libros.
   * @example
   * // Update many Libros
   * const libros = await prisma.libros.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Libros and only return the `id`
   * const librosWithIdOnly = await prisma.libros.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LibrosUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LibrosUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Libros.
   * @param {LibrosUpsertArgs} args - Arguments to update or create a Libros.
   * @example
   * // Update or create a Libros
   * const libros = await prisma.libros.upsert({
   *   create: {
   *     // ... data to create a Libros
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Libros we want to update
   *   }
   * })
   */
  upsert<T extends LibrosUpsertArgs>(args: Prisma.SelectSubset<T, LibrosUpsertArgs<ExtArgs>>): Prisma.Prisma__LibrosClient<runtime.Types.Result.GetResult<Prisma.$LibrosPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Libros.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosCountArgs} args - Arguments to filter Libros to count.
   * @example
   * // Count the number of Libros
   * const count = await prisma.libros.count({
   *   where: {
   *     // ... the filter for the Libros we want to count
   *   }
   * })
  **/
  count<T extends LibrosCountArgs>(
    args?: Prisma.Subset<T, LibrosCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LibrosCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Libros.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LibrosAggregateArgs>(args: Prisma.Subset<T, LibrosAggregateArgs>): Prisma.PrismaPromise<GetLibrosAggregateType<T>>

  /**
   * Group by Libros.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibrosGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LibrosGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LibrosGroupByArgs['orderBy'] }
      : { orderBy?: LibrosGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LibrosGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLibrosGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Libros model
 */
readonly fields: LibrosFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Libros.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LibrosClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  detalleTransaccions<T extends Prisma.Libros$detalleTransaccionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Libros$detalleTransaccionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DetalleTransaccionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  detallesCarritos<T extends Prisma.Libros$detallesCarritosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Libros$detallesCarritosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DetallesCarritoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  LibrosDigitalesAdquiridos<T extends Prisma.Libros$LibrosDigitalesAdquiridosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Libros$LibrosDigitalesAdquiridosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibroDigitalAdquiridoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ofertas<T extends Prisma.Libros$ofertasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Libros$ofertasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfertaLibroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Libros model
 */
export interface LibrosFieldRefs {
  readonly id: Prisma.FieldRef<"Libros", 'Int'>
  readonly isbn: Prisma.FieldRef<"Libros", 'String'>
  readonly nombre: Prisma.FieldRef<"Libros", 'String'>
  readonly autor: Prisma.FieldRef<"Libros", 'String'>
  readonly precio: Prisma.FieldRef<"Libros", 'Decimal'>
  readonly stock: Prisma.FieldRef<"Libros", 'Int'>
  readonly estado: Prisma.FieldRef<"Libros", 'String'>
  readonly archivoDigital: Prisma.FieldRef<"Libros", 'String'>
  readonly sinopsis: Prisma.FieldRef<"Libros", 'String'>
  readonly imagenUrl: Prisma.FieldRef<"Libros", 'String'>
  readonly categoria: Prisma.FieldRef<"Libros", 'CategoriaLibro'>
}
    

// Custom InputTypes
/**
 * Libros findUnique
 */
export type LibrosFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * Filter, which Libros to fetch.
   */
  where: Prisma.LibrosWhereUniqueInput
}

/**
 * Libros findUniqueOrThrow
 */
export type LibrosFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * Filter, which Libros to fetch.
   */
  where: Prisma.LibrosWhereUniqueInput
}

/**
 * Libros findFirst
 */
export type LibrosFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * Filter, which Libros to fetch.
   */
  where?: Prisma.LibrosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Libros to fetch.
   */
  orderBy?: Prisma.LibrosOrderByWithRelationInput | Prisma.LibrosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Libros.
   */
  cursor?: Prisma.LibrosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Libros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Libros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Libros.
   */
  distinct?: Prisma.LibrosScalarFieldEnum | Prisma.LibrosScalarFieldEnum[]
}

/**
 * Libros findFirstOrThrow
 */
export type LibrosFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * Filter, which Libros to fetch.
   */
  where?: Prisma.LibrosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Libros to fetch.
   */
  orderBy?: Prisma.LibrosOrderByWithRelationInput | Prisma.LibrosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Libros.
   */
  cursor?: Prisma.LibrosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Libros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Libros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Libros.
   */
  distinct?: Prisma.LibrosScalarFieldEnum | Prisma.LibrosScalarFieldEnum[]
}

/**
 * Libros findMany
 */
export type LibrosFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * Filter, which Libros to fetch.
   */
  where?: Prisma.LibrosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Libros to fetch.
   */
  orderBy?: Prisma.LibrosOrderByWithRelationInput | Prisma.LibrosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Libros.
   */
  cursor?: Prisma.LibrosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Libros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Libros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Libros.
   */
  distinct?: Prisma.LibrosScalarFieldEnum | Prisma.LibrosScalarFieldEnum[]
}

/**
 * Libros create
 */
export type LibrosCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * The data needed to create a Libros.
   */
  data: Prisma.XOR<Prisma.LibrosCreateInput, Prisma.LibrosUncheckedCreateInput>
}

/**
 * Libros createMany
 */
export type LibrosCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Libros.
   */
  data: Prisma.LibrosCreateManyInput | Prisma.LibrosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Libros createManyAndReturn
 */
export type LibrosCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * The data used to create many Libros.
   */
  data: Prisma.LibrosCreateManyInput | Prisma.LibrosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Libros update
 */
export type LibrosUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * The data needed to update a Libros.
   */
  data: Prisma.XOR<Prisma.LibrosUpdateInput, Prisma.LibrosUncheckedUpdateInput>
  /**
   * Choose, which Libros to update.
   */
  where: Prisma.LibrosWhereUniqueInput
}

/**
 * Libros updateMany
 */
export type LibrosUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Libros.
   */
  data: Prisma.XOR<Prisma.LibrosUpdateManyMutationInput, Prisma.LibrosUncheckedUpdateManyInput>
  /**
   * Filter which Libros to update
   */
  where?: Prisma.LibrosWhereInput
  /**
   * Limit how many Libros to update.
   */
  limit?: number
}

/**
 * Libros updateManyAndReturn
 */
export type LibrosUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * The data used to update Libros.
   */
  data: Prisma.XOR<Prisma.LibrosUpdateManyMutationInput, Prisma.LibrosUncheckedUpdateManyInput>
  /**
   * Filter which Libros to update
   */
  where?: Prisma.LibrosWhereInput
  /**
   * Limit how many Libros to update.
   */
  limit?: number
}

/**
 * Libros upsert
 */
export type LibrosUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * The filter to search for the Libros to update in case it exists.
   */
  where: Prisma.LibrosWhereUniqueInput
  /**
   * In case the Libros found by the `where` argument doesn't exist, create a new Libros with this data.
   */
  create: Prisma.XOR<Prisma.LibrosCreateInput, Prisma.LibrosUncheckedCreateInput>
  /**
   * In case the Libros was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LibrosUpdateInput, Prisma.LibrosUncheckedUpdateInput>
}

/**
 * Libros delete
 */
export type LibrosDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
  /**
   * Filter which Libros to delete.
   */
  where: Prisma.LibrosWhereUniqueInput
}

/**
 * Libros deleteMany
 */
export type LibrosDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Libros to delete
   */
  where?: Prisma.LibrosWhereInput
  /**
   * Limit how many Libros to delete.
   */
  limit?: number
}

/**
 * Libros.detalleTransaccions
 */
export type Libros$detalleTransaccionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetalleTransaccion
   */
  select?: Prisma.DetalleTransaccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetalleTransaccion
   */
  omit?: Prisma.DetalleTransaccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetalleTransaccionInclude<ExtArgs> | null
  where?: Prisma.DetalleTransaccionWhereInput
  orderBy?: Prisma.DetalleTransaccionOrderByWithRelationInput | Prisma.DetalleTransaccionOrderByWithRelationInput[]
  cursor?: Prisma.DetalleTransaccionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DetalleTransaccionScalarFieldEnum | Prisma.DetalleTransaccionScalarFieldEnum[]
}

/**
 * Libros.detallesCarritos
 */
export type Libros$detallesCarritosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DetallesCarrito
   */
  select?: Prisma.DetallesCarritoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DetallesCarrito
   */
  omit?: Prisma.DetallesCarritoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DetallesCarritoInclude<ExtArgs> | null
  where?: Prisma.DetallesCarritoWhereInput
  orderBy?: Prisma.DetallesCarritoOrderByWithRelationInput | Prisma.DetallesCarritoOrderByWithRelationInput[]
  cursor?: Prisma.DetallesCarritoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DetallesCarritoScalarFieldEnum | Prisma.DetallesCarritoScalarFieldEnum[]
}

/**
 * Libros.LibrosDigitalesAdquiridos
 */
export type Libros$LibrosDigitalesAdquiridosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibroDigitalAdquirido
   */
  select?: Prisma.LibroDigitalAdquiridoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibroDigitalAdquirido
   */
  omit?: Prisma.LibroDigitalAdquiridoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibroDigitalAdquiridoInclude<ExtArgs> | null
  where?: Prisma.LibroDigitalAdquiridoWhereInput
  orderBy?: Prisma.LibroDigitalAdquiridoOrderByWithRelationInput | Prisma.LibroDigitalAdquiridoOrderByWithRelationInput[]
  cursor?: Prisma.LibroDigitalAdquiridoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LibroDigitalAdquiridoScalarFieldEnum | Prisma.LibroDigitalAdquiridoScalarFieldEnum[]
}

/**
 * Libros.ofertas
 */
export type Libros$ofertasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfertaLibro
   */
  select?: Prisma.OfertaLibroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfertaLibro
   */
  omit?: Prisma.OfertaLibroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfertaLibroInclude<ExtArgs> | null
  where?: Prisma.OfertaLibroWhereInput
  orderBy?: Prisma.OfertaLibroOrderByWithRelationInput | Prisma.OfertaLibroOrderByWithRelationInput[]
  cursor?: Prisma.OfertaLibroWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OfertaLibroScalarFieldEnum | Prisma.OfertaLibroScalarFieldEnum[]
}

/**
 * Libros without action
 */
export type LibrosDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Libros
   */
  select?: Prisma.LibrosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Libros
   */
  omit?: Prisma.LibrosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibrosInclude<ExtArgs> | null
}
